- Makefile
- README.md
> Renaming to gomplate

- README.md
> MIT licensing

- README.md
> Adding CircleCI build

- main.go
> Releasing 0.0.2

- README.md
> 📖 Adding details to README

- Makefile
Signed-off-by: Dave Henderson <David.Henderson@qlik.com>
> Adding changelog generator make target

- .gitignore
- circle.yml
Signed-off-by: Dave Henderson <David.Henderson@qlik.com>
> Providing unit test reports in JUnit format for CircleCI

- README.md
> Updating README with docs for getenv with default

- CHANGELOG.md
> Updating CHANGELOG for v0.1.1

- env.go
- env_test.go
- main.go
- main_test.go
- typeconv.go
- typeconv_test.go
> 💄 Refactoring to split functions

- aws/ec2meta.go
- aws/ec2meta_test.go
- aws/testutils.go
- main.go
- main_test.go
> Adding ec2meta function

- README.md
- main.go
- main_test.go
- typeconv.go
- typeconv_test.go
> Adding json filter function

- README.md
> 📖 Documenting the ec2meta function

- README.md
- aws/ec2meta.go
- aws/ec2meta_test.go
- main.go
- main_test.go
Addresses #15.
Similar to #20, except this queries the `dynamic` path instead.
> Adding new ec2dynamic function

- README.md
> Updating README for ec2tag and e2region

- aws/ec2info.go
- aws/ec2meta.go
> Using defaults on network errors and timeouts

- CHANGELOG.md
> Updating changelog post-0.2.0 release

- main.go
> It's 'ec2region', not 'region'

- CHANGELOG.md
> Updating changelog for 0.2.1

- README.md
- main.go
> Fixing -v flag

- README.md
- main.go
- main_test.go
- typeconv.go
- typeconv_test.go
New functions:
- `slice`
- `jsonArray`
> Adding slice and jsonArray template functions

- Makefile
- README.md
- main.go
- version/version.go
So we don't run into issues like #33 again...
> Setting the version at build time from the latest tag

- CHANGELOG.md
> Update Changelog after 0.3.0 release

- CHANGELOG.md
> Update Changelog after 0.4.0 release

- README.md
> Adding report card badge to README

- README.md
> Adding Codebeat and GoCover badges

- main.go
Gonna need something more than the `flag` package in upcoming features, plus the `--help` output is prettier 😜 
> Switching argument parsing to codegangsta/cli

- README.md
> Adding GitHub total downloads badge

- CHANGELOG.md
> Updating changelog for 0.5.0

- aws/ec2info.go
Lazy-load the `InstanceDescriber` so we don't have to figure out the region each time...
Fixes #48 
> Make things start faster

- README.md
- data.go
- data_test.go
> Adding support for HTTP/HTTPS datasources

- circle.yml
> Getting a false positive on the tests :(

- aws/ec2info_test.go
> Fixing broken tests

- README.md
- aws/ec2meta.go
- aws/ec2meta_test.go
> Adding ability to provide default for ec2region function

- Makefile
- README.md
> Adding build-release make target

- CONTRIBUTING.md
- Makefile
- README.md
> Improving docs and adding contrib instructions

- CONTRIBUTING.md
> Improving contributing guidelines

- README.md
> Adding instructions for installing via the homebrew tap

- README.md
Added a read me section about multiple line if/else/end statements.
> Added a read me section about multiple line if/else/end statements.

- circle.yml
- context_test.go
- data.go
- data_test.go
- main.go
- main_test.go
- typeconv.go
- typeconv_test.go
Adding some nitpicking to the CI process 💄 
> Adding gometalinter to CI checks

- README.md
Re-do of PR #82 
Just some minor SEO for the README ;-)
> Mention CLI and datasources support in description

- Dockerfile
- hooks/build
Adding metadata for https://microbadger.com/images/hairyhenderson/gomplate
> Adding LABELs to help add MicroBadger metadata

- README.md
> Adding DockerHub-related badges and documenting use of the Docker image

- .gitignore
- Makefile
- glide.lock
- glide.yaml
> Vendoring dependencies with glide

- data.go
> shutting up golint

- README.md
> Documenting how to install gomplate in Alpine Linux

- README.md
- main.go
- main_test.go
> Allow overriding the template delimiters

- README.md
- vault/client.go
- vault/userpass_strategy.go
- vault/userpass_strategy_test.go
> Adding support for userpass vault auth backend

- Makefile
- test/integration/.gitignore
- test/integration/Dockerfile
- test/integration/datasources_http.bats
- test/integration/helper.bash
- test/integration/mirrorsvc/main.go
I couldn't run these tests on the plane... So I wrote this on the plane instead 😝 
> Removing integration test dependency on internet access

- README.md
- gomplate.go
- test/integration/datasources_file.bats
From https://github.com/hairyhenderson/gomplate/issues/117#issuecomment-294753830
This is entirely a convenience alias for templates that involve lots of references to datasources.
> Adding ds alias for datasource function

- Makefile
- README.md
- test/integration/datasources_vault.bats
- vault/remote_strategies.go
- vault/remote_strategies_test.go
- vault/strategy.go
- vault/token_strategy.go
- vault/token_strategy_test.go
> Supporting *_FILE env vars for vault datasource credentials

- README.md
- gomplate.go
> Add splitN function (i.e. strings.SplitN)

- README.md
- docs/content/functions/general.md
- docs/content/index.md
> Fixing up typos and formatting in docs

- data.go
- libkv/boltdb.go
- libkv/boltdb_test.go
- libkv/consul.go
- libkv/consul_test.go
- libkv/libkv.go
- libkv/libkv_test.go
- test/integration/Dockerfile
- test/integration/datasources_consul.bats
- test/integration/helper.bash
- test/integration/test.sh
Adding unit tests for the Consul and BoltDB datasource-related code. Also fixing up some of the integration tests, and doing refactoring to make things more testable.
> Adding unit tests for libkv datasources

- test/integration/datasources_vault.bats
Just a followup to #183 to round out the coverage
> Adding a couple extra integration tests for vault

- hooks/build
- hooks/post_push
> Some build fixes

- vault/auth.go
> Create file if it doesn't exist

- docs/content/functions/conv.md
Fixes #196 
Document the new functions `conv.ParseInt`, `conv.ParseFloat`, `conv.ParseUint`, and `conv.Atoi`
> Document conv.ParseInt, conv.ParseFloat, conv.ParseUint, and conv.Atoi

- docs/content/functions/time.md
- funcs.go
- funcs/time.go
- funcs/time_test.go
- test/integration/time.bats
- time/time.go
> Add time funcs

- test/integration/helper.bash
- test/integration/metasvc/main.go
This should help reduce the random build failures...
> Stabilizing integration tests a bit

- Makefile
- appveyor.yml
> Using Go 1.9.x now - go test ignores vendor on its own now

- gomplate.go
- gomplate_test.go
- net/net_test.go
- process.go
- process_test.go
- test/integration/input-dir.bats
Fixes #239 (though not very elegantly _yet_).
> Naming template after input filename

- Makefile
> Increase gometalinter timeout and make it go faster locally

- Dockerfile
> Building with Go 1.10

- Makefile
> Use lzma compression with UPX

- Makefile
> Generating changelog in container

- Makefile
- test/integration/helper.bash
Doing some `Makefile` refactoring to make things a bit easier to deal with...
> Refactoring the Makefile

- docs/content/functions/file.md
- file/file.go
- file/file_test.go
- funcs.go
- funcs/file.go
- funcs/file_test.go
- test/integration/file_test.go
Fixes #249
Adds 5 new functions:
- `file.Read`
- `file.ReadDir`
- `file.Stat`
- `file.Exists`
- `file.IsDir`
> Adding file namespace

- circle.yml
Test failures can be annoying to diagnose without this...
> Log test output in CI

- README.md
> Add FOSSA license scan badge

- funcs/strings.go
- funcs/strings_test.go
> New function proposal: `strings.TrimPrefix`

- docs/content/functions/env.md
- env/env.go
- env/env_test.go
- funcs/env.go
- test/integration/envvars_test.go
> New env.ExpandEnv function

- conv/conv.go
- conv/conv_test.go
- conv/evalargs.go
- docs/content/functions/conv.md
- funcs/conv.go
> Adding conv.ToString function

- docs/content/functions/time.md
- funcs/time.go
> Adding time.Since and time.Until funcs

- template.go
- template_test.go
- vault/auth.go
add mode to the tplate struct and update code to make use of this.
Fixes #296
> Preserve FileMode of input file when writing output file

- Dockerfile
- hooks/build
- hooks/post_push
Useful in certain scenarios... This includes the slim binary.
> Adding alpine Docker image variant

- data/data.go
- data/data_test.go
> Fixing panic when parsing empty CSVs and CSVs containing only newlines

- Dockerfile.integration
- test/integration/datasources_vault_ec2_test.go
- test/integration/datasources_vault_test.go
Fixes some incompatibilities since the `secret/` backend has been bumped to v2.
> Upgrade vault to 0.10 in integration tests

- data/datasource.go
- data/datasource_test.go
- docs/content/functions/data.md
- funcs/data.go
- test/integration/datasources_file_test.go
> Adding datasourceReachable function

- data/datasource.go
- data/datasource_vault.go
- data/datasource_vault_test.go
- docs/content/functions/data.md
- test/integration/datasources_vault_test.go
- vault/vault.go
Vault list support! Related to #215, implements #229.
> Adding vault list support

- docs/content/_index.md
- docs/content/datasources.md
- docs/content/functions/data.md
- docs/content/usage.md
I've been unhappy with the state of the docs as pertains to datasources, so I've overhauled the docs and added a separate section specifically for datasources.
> Overhauling datasource documentation

- .gitignore
- Makefile
- circle.yml
> Setting up code coverage with codeclimate

- docs/content/functions/strings.md
- funcs/strings.go
- funcs/strings_test.go
- strings/strings.go
- strings/strings_test.go
To sort arrays or slices of strings!
> Adding new strings.Sort function

- cmd/gomplate/main.go
- docs/content/usage.md
- gomplate.go
- template.go
- template_test.go
- tests/integration/basic_test.go
- tests/integration/inputdir_test.go
> Adding --chmod flag to explicitly set output file modes

- Dockerfile
- Dockerfile.integration
Been waiting for this for a while! 
https://twitter.com/hairyhenderson/status/1007353643681501184
Go 1.11 has one very gomplate-relevant change (from https://golang.org/doc/go1.11#text/template):
> Modifying template variables via assignments is now permitted via the = token:
```
{{ $v := "init" }}
{{ if true }}
{{ $v = "changed" }}
{{ end }}
v: {{ $v }} {{/* "changed" */}}
```
🎉
> Updating to Go 1.11 (allows modifying template variables!)

- Makefile
- aws/testutils.go
- cmd/gomplate/main.go
- conv/conv.go
- crypto/pbkdf2.go
- data/datasource_test.go
- funcs/crypto.go
- libkv/consul.go
- libkv/consul_test.go
- template.go
- tests/integration/datasources_env_test.go
- vault/testutils.go
> Updating gometalinter config and fixing new lint errors

- Makefile
- cmd/gomplate/main.go
- gomplate.go
- gomplate_test.go
- version/version.go
Fixes #375 
Replaces #379 and #384 - maybe this time I'll get it right 🤦‍♂️
> Adding new --verbose flag

- conv/conv.go
- conv/conv_test.go
- docs-src/content/functions/conv.yml
- docs/content/functions/conv.md
- funcs/conv.go
- tests/integration/typeconv_test.go
Finally! Related to #210 and #291
> Adding dict/conv.Dict function

- docs/content/syntax.md
- docs/content/usage.md
Fixes #242 and hopefully will help lower the barrier to entry! 
> Adding more syntax docs

- data/datasource.go
- data/datasource_test.go
- tests/integration/datasources_file_test.go
Fixes #399 - bug introduced in #358 
> Silencing defineDatasource function

- docs/content/syntax.md
> Fix a typo

- .circleci/config.yml
> Updating CircleCI config

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- funcs/strings.go
- funcs/strings_test.go
> Adding quote and squote functions

- docs-src/content/functions/conv.yml
- docs/content/functions/conv.md
- docs/content/syntax.md
> Fixing some docs bugs, and clarifying some things

- Gopkg.lock
- data/data.go
- data/data_test.go
- data/datasource.go
- data/mimetypes.go
- docs/content/datasources.md
- tests/integration/datasources_file_test.go
- vendor/github.com/joho/godotenv/LICENCE
- vendor/github.com/joho/godotenv/godotenv.go
> Adding support for .env files

- .dockerignore
- Dockerfile
Here's the fix I applied to get #484 solved 😅... Once 3.96 is finally out this can be undone!
> Use upx 3.94 from alpine 3.8 for now

- docs-src/content/functions/file.yml
- docs/content/functions/file.md
- file/file.go
- file/file_test.go
> file.Write should create non-existing subdirectories

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- funcs/strings.go
- strings/strings.go
- strings/strings_test.go
- tests/integration/strings_test.go
> New functions strings.CamelCase, strings.SnakeCase, strings.KebabCase

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
> docs: adding missing string functions to yaml source

- docs-src/content/functions/aws.yml
- docs/content/functions/aws.md
> Adding docs for aws.KMSEncrypt and aws.KMSDecrypt

- .circleci/config.yml
> Parallelize CircleCi build

- funcs/random_test.go
Just a simple logic bug in the unit test... Ran into it during a recent PR! 😂🎲
> Fixing random test that fails rarely 🎲

- funcs/random_test.go
> Fix the random.Number test (again) 🤦‍♂️

- Gopkg.lock
- coll/jsonpath.go
- coll/jsonpath_test.go
- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
- funcs/coll.go
- tests/integration/collection_test.go
- vendor/k8s.io/client-go/LICENSE
- vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
- vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
- vendor/k8s.io/client-go/util/jsonpath/doc.go
- vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
- vendor/k8s.io/client-go/util/jsonpath/node.go
- vendor/k8s.io/client-go/util/jsonpath/parser.go
> Adding coll.JSONPath function

- docs/config.toml
- docs/content/search.md
- docs/layouts/_default/index.json
- docs/layouts/partials/footer.html
- docs/layouts/partials/footer_js.html
- docs/layouts/partials/header.html
- docs/static/js/application.js
- docs/static/js/search.js
- docs/static/stylesheets/application.css
- docs/static/stylesheets/search.css
Adding some search functionality with fuse.js and mark.js by following the instructions at https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae (and making lots of modifications!)
> Adding search functionality to docs site

- template.go
- template_unix_test.go
- tests/integration/inputdir_test.go
> Fixing file-mode inheritance bug

- aws/doc.go
- base64/base64.go
- coll/coll.go
- conv/conv.go
- crypto/doc.go
- data/data.go
- env/env.go
- file/file.go
- funcs/doc.go
- gomplate.go
- math/math.go
- net/net.go
- random/random.go
- regexp/regexp.go
- strings/strings.go
- test/test.go
- tests/integration/integration.go
- time/time.go
- tmpl/tmpl.go
> Updating some package docs

- data/datasource.go
- data/datasource_consul.go
- docs/content/datasources.md
- libkv/libkv.go
- tests/integration/datasources_consul_test.go
Consul LIST support! Similar to Vault LIST support (https://github.com/hairyhenderson/gomplate/pull/332)
> Support Consul LIST

- docs/content/usage.md
> Clarifying --exclude docs

- docs/content/usage.md
> Improving the docs for --context

- .github/labeler.yml
- .github/workflows/docker.yml
- .github/workflows/label.yml
> Adding some GitHub actions

- .github/workflows/windows.yml
- net/net_test.go
_In theory_ this may be a bit more reliable than the Appveyor build... I won't turn that off just yet though since the environments are a bit different...
> Building on Windows with GitHub Action

- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
> Fix example in docs for coll.Uniq

- coll/coll.go
- coll/coll_test.go
- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
- funcs/coll.go
- funcs/coll_test.go
- go.sum
- tests/integration/collection_test.go
Adding a new `coll.Flatten` function for flattening arbitrarily-nested slices/arrays.
> New flatten/coll.Flatten function

- .github/workflows/windows.yml
This should save a few seconds...
> Set GOFLAGS=-mod=vendor on windows workflow

- Dockerfile
> Speed up docker build by not building all platforms

- cmd/gomplate/main.go
- cmd/gomplate/main_test.go
- cmd/gomplate/validate.go
- cmd/gomplate/validate_test.go
- tests/integration/basic_test.go
> refactor validateOpts

- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/client/default_retryer.go
- vendor/github.com/aws/aws-sdk-go/aws/config.go
- vendor/github.com/aws/aws-sdk-go/aws/csm/reporter.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/sts_legacy_regions.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
- vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
- vendor/github.com/aws/aws-sdk-go/aws/session/session.go
- vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
- vendor/github.com/aws/aws-sdk-go/service/s3/api.go
- vendor/github.com/aws/aws-sdk-go/service/sts/api.go
- vendor/github.com/aws/aws-sdk-go/service/sts/errors.go
- vendor/github.com/gosimple/slug/go.mod
- vendor/github.com/gosimple/slug/go.sum
- vendor/github.com/gosimple/slug/languages_substitution.go
- vendor/github.com/gosimple/slug/slug.go
- vendor/modules.txt
> Updating dependencies

- docs/content/syntax.md
Addresses #719 with some better docs.
> Documenting the initial context ($) variable

- .github/workflows/mod-tidy.yml
- go.sum
> Tidy Go modules in CI

- .dependabot/config.yml
> Putting dependabot config in git

- Dockerfile
> Use the upx binary from hairyhenderson/upx

- go.mod
- go.sum
> Updating deps

- .github/FUNDING.yml
> Adding Sponsor button

- .github/workflows/docker.yml
Missed uncommenting these in #811
> Fix docker-build push action

- Dockerfile
> build: compress slim binary with upx 3.96

- docs/content/syntax.md
> Improve documentation for upstream functions & actions

- coll/coll.go
- coll/coll_test.go
- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
- funcs/coll.go
- funcs/coll_test.go
- tests/integration/collection_test.go
> New functions coll.Pick and coll.Omit

- docs-src/content/functions/regexp.yml
- docs/content/functions/regexp.md
- funcs/regexp.go
- regexp/regexp.go
- regexp/regexp_test.go
- tests/integration/regexp_test.go
> Add function regexp.QuoteMeta

- gomplate_test.go
- internal/writers/writers.go
- internal/writers/writers_test.go
- template.go
- template_test.go
Just a bit of refactoring in preparation for some other stuff...
> Move internal writers to an internal package

- docs/content/syntax.md
> Document variable scope

- data/datasource.go
- data/datasource_boltdb.go
- data/datasource_stdin.go
- data/datasource_stdin_test.go
- data/datasource_test.go
> refactoring: extract stdin and boltdb readers

- Dockerfile
- Makefile
> Use upx 3.94 for compressing

- docs/content/installing.md
A few more tweaks based on conversation in #894
> Some more install doc clarifications

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
> Fix typos in strings examples

- docs/content/usage.md
> Document the --datasource-header flag

- data/datasource.go
- data/datasource_test.go
- docs-src/content/functions/data.yml
- docs/content/datasources.md
- docs/content/functions/data.md
> Fall back to JSON/YAML arrays when parsing datasources

- data/data.go
- data/data_test.go
Fixes #909 
This basically just takes some code from [the Hugo project](https://github.com/gohugoio/hugo/blob/cdfd1c99baa22d69e865294dfcd783811f96c880/parser/metadecoders/decoder.go#L257) (which was in turn from the [stripe-mock](https://github.com/stripe/stripe-mock/blob/24a2bb46a49b2a416cfea4150ab95781f69ee145/mapstr.go#L13) project) and modifies it slightly for gomplate's use.
> Fixing bug when parsing YAML documents with anchors

- docs/content/installing.md
Fixes #980 
Also updates references from 3.7 to 3.8 😉
> Fixing docker image tag

- README.md
- docs/content/_index.md
> Adding some links to GitHub Discussions

- .github/workflows/build.yml
- .golangci.yml
- Makefile
- coll/coll_test.go
- conv/conv.go
- conv/conv_test.go
- crypto/rsa_test.go
- data/datasource_blob.go
- data/datasource_git.go
- data/datasource_git_test.go
- data/datasource_merge.go
- data/datasource_test.go
- funcs/conv_test.go
- funcs/math_test.go
- funcs/strings.go
- internal/cmd/config_test.go
- internal/conv/conv_test.go
- internal/iohelpers/writers_test.go
- internal/tests/integration/integration_test.go
- template_test.go
- vault/auth.go
> Moving lint config to config file, fixing some issues

- Dockerfile
> Ship uncompressed binary in :alpine images

- .github/workflows/codeql-analysis.yml
> Update CodeQL GitHub Action

- docs/content/usage.md
- internal/cmd/logger.go
- internal/cmd/logger_test.go
> Support different log formats with GOMPLATE_LOG_FORMAT

- internal/tests/inprocess-integration/datasources_blob_test.go
- internal/tests/inprocess-integration/datasources_http_test.go
- internal/tests/inprocess-integration/datasources_merge_test.go
- internal/tests/inprocess-integration/datasources_vault_ec2_test.go
- internal/tests/integration/base64_test.go
- internal/tests/integration/collection_test.go
- internal/tests/integration/datasources_blob_test.go
- internal/tests/integration/datasources_http_test.go
- internal/tests/integration/datasources_merge_test.go
- internal/tests/integration/datasources_vault_ec2_test.go
- internal/tests/integration/net_test.go
- internal/tests/integration/regexp_test.go
- internal/tests/integration/strings_test.go
- internal/tests/integration/tmpl_test.go
Some minor improvements, and bringing in-process integration tests a little closer to the other tests.
> A few integration test simplifications

- file/file.go
- internal/config/configfile.go
- internal/config/configfile_test.go
- internal/iohelpers/filemode.go
- internal/iohelpers/filemode_test.go
- internal/iohelpers/skipsame_flow.md
- internal/iohelpers/template_process_flow.md
- internal/tests/integration/basic_test.go
- internal/tests/integration/inputdir_test.go
- template.go
- template_test.go
- vault/auth.go
> move NormalizeFileMode to iohelpers package

- README.md
See : Package Gomplate as a windows Chocolatey package 🎁 #1119
> Add chocolatey package badges

- docs/content/installing.md
> add some documentation to explain how to install gomplate with chocolatey, see #1119 
[Original comment](https://github.com/hairyhenderson/gomplate/issues/1119#issuecomment-813086242) : https://github.com/hairyhenderson/gomplate/issues/1119#issuecomment-813086242
> Explain how to install gomplate on Windows

- docs/content/datasources.md
> Fix 'files.IsDir' typo in doc example

- .github/workflows/docker.yml
> avoid docker login on forks

- .github/workflows/docker.yml
- .github/workflows/image-scan.yml
- .trivyignore
> Scan with trivy in CI

- docs-src/content/functions/net.yml
- docs/content/functions/net.md
- funcs/net.go
- funcs/net_test.go
- go.mod
- go.sum
Some new functions to make dealing with IP addresses and CIDR blocks easier!
> New functions net.ParseIP, net.ParseIPPrefix, and net.ParseIPRange

- data/datasource_file.go
- data/datasource_file_test.go
- file/file.go
> Fix a few filehandle leaks

- docs/content/installing.md
> Clarify install docs to use stable docker tags

- .golangci.yml
- funcs/crypto.go
- funcs/filepath_unix_test.go
- funcs/filepath_windows_test.go
- internal/tests/integration/datasources_consul_test.go
- internal/tests/integration/datasources_vault_test.go
- internal/tests/integration/inputdir_unix_test.go
- internal/tests/integration/plugins_test.go
- internal/tests/integration/plugins_windows_test.go
- template_unix.go
- template_unix_test.go
- template_windows.go
- template_windows_test.go
> Add new Go 1.17 //go:build lines

- libkv/consul.go
- libkv/consul_test.go
Fixes #1209 
Also refactors somewhat to make things a bit simpler!
> Fix CONSUL_HTTP_ADDR parsing

- .github/workflows/docker.yml
> CI updates for Docker build

- .github/workflows/docker.yml
> fix GHCR login

- data/datasource.go
- data/datasource_aws_sm.go
- data/datasource_aws_sm_test.go
- data/datasource_awssmp.go
- data/datasource_awssmp_test.go
- data/datasource_blob.go
- data/datasource_blob_test.go
- data/datasource_boltdb.go
- data/datasource_consul.go
- data/datasource_env.go
- data/datasource_env_test.go
- data/datasource_file.go
- data/datasource_file_test.go
- data/datasource_git.go
- data/datasource_git_test.go
- data/datasource_http.go
- data/datasource_http_test.go
- data/datasource_merge.go
- data/datasource_merge_test.go
- data/datasource_stdin.go
- data/datasource_stdin_test.go
- data/datasource_vault.go
- data/datasource_vault_test.go
> Propagate context into datasource read functions

- docs-src/content/functions/conv.yml
- docs/content/functions/conv.md
> conv.URL - add example of how to redact the password

- strings/strings.go
- strings/strings_test.go
Found some minor issues while playing with Go 1.18's `go test -fuzz` feature... I'll commit the actual fuzz tests once Go 1.18 is out and I've updated gomplate for it!
> Fix a few bugs found while fuzzing

- .github/workflows/build.yml
- Makefile
Build with Go 1.18rc1 in preparation for 1.18 release
> Build with Go 1.18rc1

- docs/content/config.md
Not sure how I missed this, but these links are broken 🤦‍♂️ 
> Fix broken links in config.md

- docs-src/content/functions/crypto.yml
- docs/content/functions/crypto.md
> docs: remove duplicate function doc

- .golangci.yml
- conv/conv.go
- data/datasource.go
- data/datasource_boltdb.go
- funcs/conv.go
- funcs/strings.go
- funcs/strings_test.go
- internal/deprecated/deprecated.go
- internal/tests/integration/datasources_boltdb_test.go
- libkv/boltdb.go
- strings/strings.go
Also mark a few more things deprecated! These will be documented in the v3.11 release notes.
> Log warning message when a deprecated function or datasource is used

- .github/workflows/build.yml
- funcs/math_test.go
- gomplate_test.go
- internal/tests/integration/config_test.go
- internal/tests/integration/datasources_consul_test.go
- internal/tests/integration/datasources_git_test.go
- internal/tests/integration/datasources_vault_test.go
- internal/tests/integration/integration_test.go
> Removing some panics from tests

- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/image-scan.yml
- .github/workflows/label.yml
> Fix GHA workflow triggers

- plugins.go
- plugins_test.go
Adds a new `gomplate.PluginFunc` function to create custom template functions. This exports existing functionality to make it slightly easier to use gomplate programatically.
> PluginFunc to create custom template functions

- context.go
- context_test.go
- data/datasource.go
- data/datasource_http.go
- data/datasource_http_test.go
- data/datasource_stdin.go
- data/datasource_stdin_test.go
- data/datasource_test.go
- gomplate.go
- internal/cmd/config.go
- internal/cmd/config_test.go
- template.go
A bunch of refactoring & cleanup... This should help untangle a few things on the way to better programmatic usability...
> General refactoring & cleanup

- crypto/pbkdf2_test.go
- crypto/rsa_test.go
- funcs/aws_test.go
- funcs/base64_test.go
- funcs/coll_test.go
- funcs/conv_test.go
- funcs/crypto_test.go
- funcs/data_test.go
- funcs/env_test.go
- funcs/file_test.go
- funcs/filepath_test.go
- funcs/filepath_unix_test.go
- funcs/filepath_windows_test.go
- funcs/gcp_test.go
- funcs/math_test.go
- funcs/net_test.go
- funcs/path_test.go
- funcs/random_test.go
- funcs/regexp_test.go
- funcs/sockaddr_test.go
- funcs/strings_test.go
- funcs/test_test.go
- funcs/time_test.go
- funcs/uuid_test.go
- internal/tests/integration/plugins_test.go
This may be a terrible idea, but I got a bit carried away a few weeks back 😅 
> Parallelizing more tests

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/image-scan.yml
- .github/workflows/label.yml
> Enable CI for 3.11.x branch

- render_test.go
Who knew a vessel's draught could change? 🤷‍♂️
> Fix flakey example

- .github/workflows/build.yml
- .github/workflows/lint.yml
> Switch to golangci-lint GitHub Action

- .github/workflows/build.yml
- .github/workflows/lint.yml
Backport of https://github.com/hairyhenderson/gomplate/pull/1472
> [3.11.x backport] Switch to golangci-lint GitHub Action

- cmd/gomplate/main.go
- data/data.go
- data/datasource_file.go
- data/datasource_git.go
- data/datasource_git_test.go
- data/datasource_http.go
- data/datasource_stdin.go
- env/env.go
- file/file.go
- file/file_test.go
- funcs/aws.go
- funcs/crypto.go
- funcs/doc.go
- funcs/net.go
- gcp/meta.go
- internal/tests/integration/basic_test.go
- internal/tests/integration/config_test.go
- internal/tests/integration/file_test.go
- internal/tests/integration/inputdir_test.go
- internal/tests/integration/inputdir_unix_test.go
- vault/auth.go
> Lint fixes (for 3.11.x)

- .github/workflows/lint.yml
- cmd/gomplate/main.go
- data/data.go
- data/datasource_file.go
- data/datasource_git.go
- data/datasource_git_test.go
- data/datasource_http.go
- data/datasource_stdin.go
- env/env.go
- file/file.go
- file/file_test.go
- funcs/aws.go
- funcs/crypto.go
- funcs/doc.go
- funcs/net.go
- gcp/meta.go
- internal/tests/integration/basic_test.go
- internal/tests/integration/config_test.go
- internal/tests/integration/file_test.go
- internal/tests/integration/inputdir_test.go
- internal/tests/integration/inputdir_unix_test.go
- vault/auth.go
> Use Go 1.19 when linting

- README.md
> Remove microbadger links

- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
> Fix incorrect coll.GoSlice example

- docs-src/content/functions/coll.yml
Trivial, but might as well touch it up.
> Fix minor typo: Pic -> Pick

- docs/content/syntax.md
Related to https://github.com/hairyhenderson/gomplate/discussions/1545
Clarifies the docs, as mentioned here: https://github.com/hairyhenderson/gomplate/discussions/1545#discussioncomment-4007859
> Clarify documentation to highlight the differences between 'index' and '.'

- .github/workflows/build.yml
- .github/workflows/lint.yml
- internal/tests/integration/datasources_vault_test.go
> CI updates

- Makefile
- go.mod
- go.sum
- version/gen/vgen.go
- version/gen/vgen_test.go
Fixing how versioning works on prerelease builds...
> Generate prerelease versions

- .github/workflows/stale.yml
There are lots of stale issues and PRs in the repo - this'll help clean them up.
> Add stale action

- docs/content/installing.md
- https://github.com/teaxyz/pantry/pull/834
> :gift: Add tea.xyz package manager :tea: 

- .github/workflows/stale.yml
Related to https://github.com/hairyhenderson/gomplate/discussions/1773
> Updates to stale workflow

- docs/content/functions/_index.md
> docs: Fix broken link

- go.mod
- go.sum
- version/gen/vgen.go
- version/gen/vgen_test.go
> build: bump `github.com/Masterminds/semver` to `github.com/Masterminds/semver/v3`

- Makefile
> Add support for Linux s390x

- .github/workflows/lint.yml
- .golangci.yml
- render_test.go
Fix an Example that broke due to an external API change
> Fix broken test

- cmd/gomplate/main.go
Fixes #1848 (the panic-swallowing part, the cause for the panic was fixed in https://github.com/hairyhenderson/gomplate/pull/1480)
> Remove defers from main() to stop suppressing panics

- Makefile
Backporting #1837 into 3.11.x (for #1836)
> backport: Add support for Linux s390x

- internal/cmd/config.go
- internal/config/configfile.go
- internal/tests/integration/config_test.go
> Clarify config parsing errors

- render_test.go
The previous public API was changing too often. This should be more static!
> Fix renderer example

- funcs.go
- internal/funcs/aws.go
- internal/funcs/base64.go
- internal/funcs/coll.go
- internal/funcs/conv.go
- internal/funcs/crypto.go
- internal/funcs/data.go
- internal/funcs/env.go
- internal/funcs/file.go
- internal/funcs/filepath.go
- internal/funcs/gcp.go
- internal/funcs/math.go
- internal/funcs/net.go
- internal/funcs/path.go
- internal/funcs/random.go
- internal/funcs/regexp.go
- internal/funcs/sockaddr.go
- internal/funcs/strings.go
- internal/funcs/test.go
- internal/funcs/test_test.go
- internal/funcs/time.go
- internal/funcs/uuid.go
- internal/funcs/uuid_test.go
Removing some deprecated template and Go functions
> Remove deprecated functions

- docs/content/config.md
- internal/config/configfile.go
- internal/config/configfile_test.go
- internal/config/types.go
- internal/config/types_test.go
- internal/tests/integration/config_test.go
- render.go
- render_test.go
- template.go
- template_test.go
Reverts hairyhenderson/gomplate#1976
> Revert "Remove support for deprecated key/value array form of template config"

- docs/content/functions/coll.md
> docs: update documentation for new coll.Pick/Omit slice support

- .github/workflows/docs.yml
- Makefile
There's some unnecessary evaluation going on here - cleaning that up.
> ci(fix): streamline the docs workflow

- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
- internal/funcs/coll.go
- internal/funcs/coll_test.go
- internal/tests/integration/collection_test.go
> feat(coll): New coll.Set and coll.Unset functions

- .github/workflows/release-please.yml
Some syntax issues - this is tough to test because it only runs on release, and I don't want to make lots of noisy releases 😓
> ci(fix): Fix broken CI release process

- Makefile
- docs/config.toml
- docs/go.mod
- docs/go.sum
- docs/layouts/partials/custom-footer.html
- netlify.toml
Also disables Google Analytics.
> docs(fix): Update docs configs to work with the latest hugo theme version

- .github/workflows/docker-main.yml
- .github/workflows/docker-release.yml
- .github/workflows/docker.yml
- .github/workflows/release-please.yml
The release build takes a while to build all of the different supported platforms. This parallelizes it to give a ~13x speedup.
> ci(release): parallelize release build

- .github/workflows/release-please.yml
left over from debugging in #2170 🤦‍♂️
> ci(fix): re-enable release-please workflow

- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
> docs(fix): Fix example output for coll.Merge

- docs-src/content/functions/test.yml
- docs/content/functions/test.md
Sorry, one more on my travels through the docs! :)
> docs(fix): Typo of description in functions/test

- internal/datafs/stdinfs.go
- internal/datafs/stdinfs_test.go
An additional fix related to #2273. https://github.com/hairyhenderson/gomplate/pull/2287 fixes one of the problems, which was that the file was being opened multiple times. Additionally, `stdinfs` should cache the content of stdin so it can be read from multiple times.
> fix(fs): Cache data in stdinfs

- .github/workflows/docker-main.yml
- .github/workflows/release.yml
- version/gen/vgen.go
> ci(fix): Attempt to fix release workflows

- internal/tests/integration/datasources_blob_test.go
The old bucket's gone, I guess... replacing with one that exists, and adding some resiliency so that bucket removals aren't fatal.
> fix(test): Use a bucket that exists for the S3 bucket test
