hairyhenderson/gomplate

- README.md
- main.go
- main_test.go
Two new functions:
- `getenv` - a more forgiving way to get an environment variable
- `bool` - converts a string into a boolean
Also enabled multi-line templates by reading the entire input before
applying the template, instead of applying the template one line at a
time.
> Adding new functions `bool` and `getenv`

- main.go
- main_test.go
> Adding support to getenv for a default value

- aws/ec2info.go
- aws/ec2info_test.go
- aws/ec2meta.go
- aws/ec2meta_test.go
- main.go
- main_test.go
> Adding ec2tag and ec2region functions

- main.go
- typeconv.go
- typeconv_test.go
New functions:
- `join` - identical to [`strings.Join`](https://golang.org/pkg/strings#Join), except that each element is converted to a string first (i.e. `[]interface{}` is supported, not just `[]string`)
- `title` - exposed [`strings.Title`](https://golang.org/pkg/strings/#Title)
- `toLower` - exposed [`strings.ToLower`](https://golang.org/pkg/strings/#ToLower)
- `toUpper` - exposed [`strings.ToUpper`](https://golang.org/pkg/strings/#ToUpper)
> New functions join, title, toLower, and toUpper

- Makefile
This affected the 0.3.0 release, but not 0.4.0 (cuz I compiled the 0.4.0 binaries after making this fix).
> Fixing broken versions in build-x target

- README.md
- data.go
- data_test.go
- main.go
Resolves #8
So far works only for JSON files, and since most filesystems don't store MIME types, only files with `.json` extension will be parsed!
> New datasource function - allows use of JSON files as a data source for the template

- README.md
- data.go
- data_test.go
- main.go
- main_test.go
- typeconv.go
- typeconv_test.go
Fixes #43 
This adds:
- new `yaml` function
- new `yamlArray` function
- support for `.yml`/`.yaml` datasources
> Adding YAML support

- aws/ec2info.go
- aws/ec2info_test.go
- aws/ec2meta.go
- aws/testutils.go
This fixes part of #59 by not even trying to connect to the EC2 instance metadata API or the EC2 API if gomplate can't connect to the EC2 instance metadata API.
> Short-circuit ec2 function defaults when not in AWS

- aws/ec2info.go
- aws/ec2info_test.go
- aws/ec2meta.go
- aws/ec2meta_test.go
- aws/testutils.go
- main.go
This is the second half of the fix for #59. Now, repeated calls to `ec2*` functions will not incur multiple network requests. This probably won't have a big impact on most templates, but it's probably 
nice to not bombard the EC2 API with tons of calls...
Fixes #59 
> Caching responses from EC2

- aws/ec2info.go
- aws/ec2info_test.go
Initializing the metaClient field with NewEc2Meta() instead of with a struct literal, so that the cache field in the embedded Ec2Meta instance is properly initialized.
I looked at why the tests didn't catch this and it appears that this would be a difficult case to catch in a non-EC2 environment.  Specifically, https://github.com/hairyhenderson/gomplate/blob/master/aws/ec2info.go#L62 short circuits the code path that would have caused the test to fail.
> Fixing a panic in Ec2Info.go

- aws/ec2info_test.go
Followup to #62 to format `ec2info_test.go` with `gofmt -s -w .`
> Formatting with gofmt -s

- main.go
`github.com/codegangsta/cli` now redirects to `github.com/urfave/cli` - updating for clarity
> Updating codegangsta/cli reference to urfave/cli

- README.md
- cleanup.go
- data.go
- main.go
- vault/app-id_strategy.go
- vault/app-id_strategy_test.go
- vault/client.go
- vault/client_test.go
- vault/token_strategy.go
- vault/token_strategy_test.go
Partial implementation of #54
This adds support for a new URL scheme `vault://` to allow reading from Hashicorp's [Vault](https://vaultproject.io), to allow injection of secrets into templates rendered by gomplate.
Right now this only supports the [`app-id`](https://www.vaultproject.io/docs/auth/app-id.html) auth backend and pre-defined tokens.
The new `vault://` URL scheme represents the base path for the vault datasource, to make it simpler to scope secrets from the same base namespace. A further path can be specified as the second argument to the `datasource` function.
For example:
```console
$ export VAULT_ADDR=https://myvaultserver.example.com:8200
$ echo '{{(datasource "vault" "secret/password").value}}' | gomplate -d vault=vault:///
foo
$ echo '{{(datasource "vault").value}}' | …
```
> Support for Vault datasources (app-id & token auth)

- main.go
- main_test.go
The original `gomplate` didn't support multi-line template strings, but in #10 I added proper support for multi-line templates. I didn't remove the `\n` that was added, though, so an extra newline was always printed at the end of the output! _Oops._
> Removing vestigial newline addition

- vault/app-id_strategy.go
- vault/client.go
- vault/http.go
- vault/http_test.go
Fix issue #75.
There are two golang HTTP related issues that are involved here, due to the way golang 1.7 http package reacts to HTTP redirects:
- https://github.com/golang/go/issues/4800
- https://github.com/golang/go/issues/7912 or https://github.com/golang/go/issues/9348
The first issue causes the `X-Vault-Token` header to be dropped when following redirects of HTTP GET requests. The second issue causes redirects on POST requests not to be followed _at all_.
It does look like golang 1.8 will address both these issues once it is released... so these fixes are just needed in the meantime.
TODO:
**PTAL**: @hairyhenderson
> Handle redirects from vault server versions earlier than v0.6.2

- vault/token_strategy.go
- vault/token_strategy_test.go
Fixes #79 
This implements a `homeDir()` function as a stand-in for my usage of `user.Current()`, which blows up when cross-compiling without `cgo`.
> Avoiding CGO landmine

- vault/client.go
- vault/client_test.go
A second attempt at a fix for #84. PTAL @hairyhenderson 
This time, rather than twisting gomplate into a pretzel trying to propagate errors, a small testing hack is being made to allow `log.Fatal` to be overwritten inside tests to inject a mock/spy that doesn't cause the process to exit.
Added unit tests and also checked on the command-line that gomplate doesn't panic when some/all of the `VAULT_*` environment variables are missing:
```
echo -n '{{(datasource "vault" "secret/foo").value}}' | gomplate -d vault="vault://"
2016/11/22 09:49:45 VAULT_ADDR is an unparseable URL!
export VAULT_ADDR=https://localhost:8500
echo -n '{{(datasource "vault" "secret/foo").value}}' | gomplate -d vault="vault://"
2016/11/22 09:49:37 No vault auth strategy configured
```
> No vault addr dont panic

- data.go
This use case was broken:
_where:_
_secret/foo.value == hi_
_secret/bar.value == hello_
```console
$  echo -ne '{{(datasource "vault" "foo").value}}\n{{(datasource "vault" "bar").value}}\n' | bin/gomplate -d vault=vault:///secret
hi
hi
```
😞 
This fixes it!
```console
$ echo -ne '{{(datasource "vault" "foo").value}}\n{{(datasource "vault" "bar").value}}\n' | bin/gomplate -d vault=vault:///secret
hi
hello
```
> Fixing bug where vault data is incorrectly cached

- Makefile
UPX 3.92 was recently released - it now supports slimmed-down macOS binaries too 🎉 
> Building a slim macOS binary too

- README.md
- main.go
- typeconv.go
- typeconv_test.go
Adding `toJSON` and `toYAML` which marshal object into their stringified JSON or YAML representations.
> Adding toJSON and toYAML functions

- README.md
- main.go
- main_test.go
- typeconv.go
- typeconv_test.go
For this kind of situation:
```go
{{ $data := datasource "foo" "bar" }}
{{ if (has $data "baz") }}
{{ $data.baz }}
{{ end }}
```
> Adding 'has' func to determine if an object has a named key

- README.md
- vault/app-id_strategy.go
- vault/app-id_strategy_test.go
- vault/testutils.go
Set `VAULT_AUTH_APP_ID_MOUNT` to customize the mount-point. Defaults to `app-id`.
> Allow custom auth backend mount point for app-id backend

- README.md
- vault/client.go
- vault/github_strategy.go
- vault/github_strategy_test.go
Adding support for the [`github`](https://www.vaultproject.io/docs/auth/github.html) Vault auth strategy.
Related to #54 
> Adding support for GitHub auth strategy for Vault datasources

- README.md
- vault/app-id_strategy_test.go
- vault/approle_strategy.go
- vault/approle_strategy_test.go
- vault/client.go
- vault/client_test.go
- vault/github_strategy_test.go
- vault/userpass_strategy_test.go
Fixes #54
I'm not _super_ familiar with the mechanics of how AppRole gets used in real-life, hopefully this is a generic enough implementation. I guess the reality is that different people will be getting `secret_id` in different ways, so that'll always have to be done out-of-band.
This PR also cleans up a bunch of leaked environment variables in unit tests... 
> Adding support for AppRole vault auth backend

- aws/ec2info.go
Fixes #110 
This does two things:
1. caches the `InstanceDescriber` in case `describer` is called multiple times, and caches it _earlier_ so that the `e.metaClient.nonAws` bool can be set earlier, avoiding unnecessary calls.
2. gives the EC2 client an `http.Client` with a 500ms timeout
On my mac, this reduces the amount of time it takes to timeout a `ec2tag` function from 900ms to 500ms.
And in Linux, it's down from 21s to 500ms.
> Performance fixes for running ec2tag in non-aws environments

- README.md
- main.go
- main_test.go
This adds 3 new commandline options:
- `--file`/`-f`: Filename of the template to process (lets you specify a file instead of forcing stdin). Can still use stdin by choosing `-` (the default)
- can be given multiple times to process multiple templates (requires the same number of `--out` args)
- `--in`/`-i`: An input string to process (avoids having to pipe from `echo`)
- `--out`/`-o`: Allows saving the output to a file. Can still use stdout by choosing `-` (the default)
> Adding more ways to specify input/output

- Makefile
- circle.yml
- test/integration/.gitignore
- test/integration/Dockerfile
- test/integration/basic.bats
- test/integration/datasources_vault.bats
- test/integration/envvars.bats
- test/integration/helper.bash
- test/integration/test.sh
It's high time some "integration" tests were part of the build. As in, actually running the `gomplate` command in various scenarios that should work - especially ones that are hard to test during unit tests...
First off, I want to be able to test the Vault integration with a real Vault server (in dev mode). So that's what most of these tests are.
This also moves the CI build to CircleCI 2.0.
> Adding some very basic integration tests

- README.md
- data.go
- data_test.go
- main.go
- test/integration/datasources_http.bats
Fixes #113
Adds new a command-line option `--datasource-header`/`-H`, which allows sending custom headers when accessing HTTP[S] datasources. For example:
```console
$ gomplate -d foo=https://httpbin.org/get -H 'foo=Foo: bar' -i '{{(datasource "foo").headers.Foo}}'
bar
```
This can be used e.g. for authentication, by setting the `Authorization` or related headers...
> Support arbitrary headers with HTTP datasources

- README.md
The link to `--datasource`/`-d` in the table of contents was broken.
@hairyhenderson PTAL
> Fix readme ToC link to `--datasource-d`

- data.go
read-write is not required here and in fact prevents many use cases
to work when the file is not writable by the user (because the call will fail in this case)
> Open datasource file in read-only mode

- README.md
- main.go
- main_test.go
- process.go
- process_test.go
- test/files/input-dir/config.yml
- test/files/input-dir/in/inner/nested.txt
- test/files/input-dir/in/top.txt
- test/integration/input-dir.bats
- Use these options when a whole directory hierarchy needs to be processed.
- Extracted file processing logic in an extra process.go
Partial solution to #117
Bear with me, Golang is not my mother tongue (which was in fact Perl at those days, but is Java & JavaScript since some times). Looking forward to a review ;-)
> Add --input-dir and --output-dir as options

- README.md
- gomplate.go
> Add urlParse function (i.e. url.Parse)

- data_test.go
- gomplate_test.go
- test/integration/datasources_file.bats
- test/integration/typeconv_funcs.bats
- typeconv.go
- typeconv_test.go
Fixes #134
This loosens the signature of `has` so that any `map` can be provided. It means using `reflect` (😨), but I think it's necessary in this case.
I also found an issue where `{{ (ds "d").foo.bar }}` would fail, so I fixed that. The fix involved moving from `json.Unmarshal` to `yaml.Unmarshal` - seems they behave slightly differently. This is just fine, given that YAML is a superset of JSON. The only catch is that the parser isn't as strict so things that failed to parse before will now parse... ¯\\\_(ツ)_/¯
> Fixing bug with 'has' and 'datasource' around referencing sub-maps in nested maps

- Dockerfile
This uses multi-stage builds to make the `hairyhenderson/gomplate` docker image smaller (from ~370MB to ~15MB).
> Making the built Docker image smaller

- README.md
- gomplate.go
- test/integration/typeconv_funcs.bats
- typeconv.go
- typeconv_test.go
Pretty-printed JSON is sometimes useful. This makes it possible.
> Adding new toJSONPretty function

- README.md
- gomplate.go
- test/integration/typeconv_funcs.bats
- typeconv.go
- typeconv_test.go
Adding a multiline-aware `indent` func.
> Adding new indent function

- README.md
- gomplate.go
- stringfunc.go
- stringfunc_test.go
This pull request adds a `replace` function which takes three arguments - an original string, the substring to replace, and the string with which to replace it. This is of particular use when generating node names from IP addresses where the node name may not contain "." characters.
The `strings.Replace` function in the Go standard library seems like it would be better named `strings.ReplaceN`, so we wrap it to replace all occurences of the string. If necessary, a gomplate function named `replaceN` could be introduced calling `strings.Replace` directly.
> Add "replace" function and documentation

- Makefile
It would be great if there was an official release for `solaris/amd64` which is the platform I'm using primarily - this PR adds it as a target in `Makefile`, which as far as I can see is the only change which needs making?
> Add `solaris-amd64` build target

- data.go
- data_test.go
- docs/content/functions.md
- docs/content/usage.md
- gomplate.go
- test/integration/datasources_file.bats
Fixes #142.
New function: `include` - works exactly like `datasource`, except the data is not parsed. Useful for unstructured data.
> Add include function

- aws/ec2info_test.go
- aws/testutils.go
- docs/config.toml
- docs/content/functions/aws.md
- docs/content/functions/general.md
- docs/content/index.md
- docs/content/installing.md
- docs/content/syntax.md
- docs/content/usage.md
- funcs.go
- funcs/aws.go
- funcs/aws_test.go
- gomplate.go
This is an offshoot of #145 to try and figure out the best way to namespace built-in functions.
Ideally, I'd like to be able to use the existing function names, and simply move them under a namespace. So, instead of `{{ ec2region }}`, I'd like `{{ aws.ec2region }}`.
> Namespacing the aws funcs

- base64/base64.go
- base64/base64_test.go
- docs/content/functions/base64.md
- funcs.go
- funcs/base64.go
- funcs/base64_test.go
- test/integration/base64.bats
Fixes #155.
New functions:
- `base64.Encode`
- `base64.Decode`
I've made a tradeoff with `Decode` for usability's sake - it returns a `string`, which renders it essentially useless for dealing with binary data _but_ very convenient for dealing with textual data. I'm not really sure which is best - a compromise could be to expose a `toString` function that can convert a `[]byte` to `string`, but that doesn't sound that great as far as usability...
> Adding new base64.Encode/base64.Decode functions

- docs/content/functions/net.md
- funcs.go
- funcs/net.go
- funcs/net_test.go
- net/net.go
- net/net_test.go
- test/integration/net.bats
Fixes #157 
Adds 6 new functions for resolving hostnames and various DNS records:
- `net.LookupIP`
- `net.LookupIPs`
- `net.LookupCNAME`
- `net.LookupSRV`
- `net.LookupSRVs`
- `net.LookupTXT`
> Adding net.Lookup* functions

- docs/content/functions/regexp.md
- funcs.go
- funcs/regexp.go
- funcs/regexp_test.go
- regexp/regexp.go
- regexp/regexp_test.go
- test/integration/regexp.bats
Fixes #152 
Adds 2 new functions:
- `regexp.Replace`
- `regexp.Match`
> Adding regexp support

- docs/content/functions/general.md
- docs/content/functions/strings.md
- funcs.go
- funcs/strings.go
- funcs/strings_test.go
- strings/strings.go
- strings/strings_test.go
- test/integration/strings.bats
- test/integration/typeconv_funcs.bats
- typeconv.go
- typeconv_test.go
Fixes #165 
- Relocates `indent` to `strings.Indent`
- Adds optional `width` argument
- Makes `indent` optional, defaults to `" "`
> Enhancing indent function

- aws/ec2info.go
- aws/ec2info_test.go
- aws/ec2meta.go
- aws/ec2meta_test.go
- aws/testutils.go
- docs/content/functions/aws.md
- funcs/aws.go
Fixes #168 by making the HTTP client timeout for AWS API calls configurable.
> Adding AWS_TIMEOUT environment variable

- Makefile
Setting `CGO_ENABLED=0` makes this static.
> Disabling cgo so the binary is truly static

- docs/content/functions/env.md
- env/env.go
- env/env_test.go
- test/integration/Dockerfile
This adds support for an optional `<envvar>_FILE` fallback when `<envvar>` is unset. The path in `<envvar>_FILE` is returned as the value.
/cc @stuart-c
> Adding support for _FILE fallback to env.Getenv function

- appveyor.yml
This should make builds more stable - didn't realize Go was already installed!
> Using the built-in Go version in Appveyor builds

- data.go
ReadSource is passed a VFS argument (set from source.FS) as the first argument, but this is never used. Instead source is passed so the readFile proc uses that instead (and directly accesses source.FS)
> Remove VFS argument from ReadSource which isn't used

- data.go
- docs/content/functions/general.md
- test/integration/datasources_vault.bats
- vault/vault.go
This requires #177 to be merged first.
This PR adds write support to the Vault datasource, enabling use of dynamic secrets (such as database credentials).
> Vault write support

- Gopkg.lock
- Makefile
- aws/ec2meta.go
- docs/content/functions/general.md
- test/integration/.gitignore
- test/integration/Dockerfile
- test/integration/awssvc/main.go
- test/integration/datasources_vault.bats
- test/integration/helper.bash
- test/integration/metasvc/main.go
- vault/auth.go
- vendor/github.com/fullsailor/pkcs7/.gitignore
- vendor/github.com/fullsailor/pkcs7/.travis.yml
- vendor/github.com/fullsailor/pkcs7/LICENSE
- vendor/github.com/fullsailor/pkcs7/README.md
- vendor/github.com/fullsailor/pkcs7/ber.go
- vendor/github.com/fullsailor/pkcs7/ber_test.go
- vendor/github.com/fullsailor/pkcs7/pkcs7.go
- vendor/github.com/fullsailor/pkcs7/pkcs7_test.go
This requires #177 to be merged first.
Add AWS ec2 auth support for Vault.
> Vault AWS EC2 auth

- docs/content/functions/general.md
- libkv/consul.go
- test/integration/datasources_consul.bats
- test/integration/helper.bash
This requires #177 to be merged first.
Add ability to get Consul token from Vault dynamic secret backend
> Consul vault auth

- data/datasource.go
- data/datasource_test.go
- test/integration/datasources_vault.bats
- vault/auth_test.go
- vault/testutils.go
- vault/vault.go
- vault/vault_test.go
Fixes #200 
New behaviour:
```console
$  bin/gomplate -d vault=vault:///secret/path/to/secret -i '{{ ds "vault" "foo" }}'
2017/09/02 18:58:12 No value found for [foo] from datasource 'vault'
```
> Fixing crash on 404

- env/env.go
> Remove trailing spaces

- .gitignore
- main.go
- test/integration/basic.bats
Fixes #192 
Test case:
```
gomplate -in flibbit
```
This PR causes gomplate to exit with a non-zero exit status and display an error message to the user:
```
Error: unknown argument 'flibbit'
```
> Fixes #192 - fail with unknown args

- conv/conv.go
- conv/conv_test.go
- `ToInt64` couldn't handle strings with floats (i.e. "3.0")
- `ToFloat64` couldn't handle strings with integers in hex or octal notation
> Fixing bugs in ToInt64/ToFloat64

- gomplate.go
- test/integration/envvars.bats
Instead of spitting out an ugly stack trace when handling an error, it's more helpful to simply print out the error and the usage message.
Before:
```console
$ gomplate -i '{{.Env.foo}}'
panic: template: template:1:6: executing "template" at <.Env.foo>: map has no entry for key "foo"
goroutine 1 [running]:
main.(*Gomplate).RunTemplate(0xc4202a3e30, 0x7fff5fbff584, 0xc, 0x1e95de0, 0xc42000c018)
/go/src/github.com/hairyhenderson/gomplate/gomplate.go:31 +0x42c
main.renderTemplate(0xc4202a3e30, 0x7fff5fbff584, 0xc, 0x197bc94, 0x1, 0x0, 0x0)
/go/src/github.com/hairyhenderson/gomplate/gomplate.go:66 +0xbc
main.processInputFiles(0x7fff5fbff584, 0xc, 0xc4202ba350, 0x1, 0x1, 0xc4202ba380, 0x1, 0x1, 0xc4202a3e30, 0xc42025e3c0, ...)
/go/src/github.com/hairyhenderson/gomplate/process.go:23 +0x152 …
```
> Don't panic on template errors

- docs/content/functions/math.md
- funcs.go
- funcs/math.go
- funcs/math_test.go
- math/math.go
- math/math_test.go
- test/integration/math.bats
New `math` namespace with basic arithmetic, wrapping `+`, `-`, `*`, `/`, `%` and `math.Pow`.
> Adding math functions

- docs/content/functions/time.md
- funcs/time.go
- test/integration/time.bats
- time/time.go
- time/time_test.go
Adding new `time.ZoneOffset` function to return the current timezone's offset in seconds east of UTC.
> Adding time.ZoneOffset function

- docs/content/functions/time.md
- funcs/time.go
- test/integration/time.bats
`time.Parse` assumes UTC when no timezone is given in the input. This can be surprising, and there can be use cases to either use the local zone or a named zone. These functions help with that!
> Add time.ParseLocal and time.ParseInLocation functions

- conv/conv.go
- conv/conv_test.go
Seemed weird that `conv.Join` could only handle `[]string` and `[]interface{}` input... _So I fixed it._
> Fixing conv.Join to handle non-interface{} arrays

- docs/content/functions/math.md
- funcs/math.go
- funcs/math_test.go
- math/math.go
- math/math_test.go
- test/integration/math.bats
New `math.Seq`/`seq` function to generate integer sequences. Similar to [`seq(1)`](https://linux.die.net/man/1/seq) in intent.
> Adding math.Seq function

- data/datasource.go
- data/datasource_test.go
- docs/content/functions/data.md
Fixes #230 
Adds support for a `stdin:` scheme for datasources. For now, MIME type is specified by setting a bogus filename and the extension is used. If no parsing is required (i.e. if the data is being included verbatim with the `include` function), just `stdin:` is enough.
```console
$ echo 'foo: bar' | gomplate -i '{{(ds "data").foo}}' -d data=stdin:///foo.yaml 
bar
$ echo 'foo' | gomplate -i '{{ include "data" }}' -d data=stdin:
foo
```
> Adding support for stdin: scheme for datasources

- docs/content/usage.md
- gomplate.go
- main.go
- process.go
- process_test.go
- test/files/input-dir/in/exclude.txt
Partially resolves issue #218 
Not sure if this is what you are after, but I've added the command line flag for exclude, which acts like a glob. so usage could be `gomplate --exclude "**/*.no"`, which would stop any files ending in .no being parsed. It uses the go `filepath.Glob` function as you recommended. Like I said, I'm not entirely sure if this is what's needed, so I'm happy to work on it or even bin it off if needs be.
- exclude takes a glob and ensures that any files found in that glob
aren't parsed
- Also added a test
> Can now pass --exclude as a flag

- data/datasource.go
- data/datasource_test.go
- docs/content/functions/data.md
- test/integration/datasources_consul.bats
Sometimes it's handy to be able to set or override a datasource's MIME type. This PR makes it possible:
```console
$ echo 'foo: bar' | bin/gomplate -i '{{(ds "config").foo}}' -d config=stdin:///?type=application/yaml                 
bar
```
> Support setting MIME type with URL query string

- data/datasource.go
- docs/content/functions/data.md
- libkv/consul.go
- test/integration/Dockerfile
- test/integration/datasources_consul.bats
- test/integration/datasources_vault.bats
- test/integration/helper.bash
- test/integration/mirrorsvc/main.go
- test/integration/test.sh
- vault/vault.go
- vault/vault_test.go
Also updating the Vault & Consul clients used in the tests, and updating the tests for new syntax.
> Allow vault address to be specified in the vault:// URL

- test/integration/awssvc/main.go
- test/integration/metasvc/main.go
- test/integration/mirrorsvc/main.go
Makes life a bit easier when running on macOS - prevents firewall pop-ups asking for permission to listen to ports...
> bind test binaries explicitly to 127.0.0.1

- test/integration/awssvc/main.go
- test/integration/helper.bash
- test/integration/metasvc/main.go
- test/integration/mirrorsvc/main.go
Sometimes tests fail (like in https://circleci.com/gh/hairyhenderson/gomplate/925), and I'm pretty sure it's because the `/quit` endpoint closes the `net.Listener` too early (before `wget` is finished).
> Attempting to fix intermittent Integration Test failure

- Dockerfile
The only necessary file other than the `gomplate` binary itself is the CA Cert bundle, so no need to base this on Alpine Linux. Also, `scratch` is smaller 😉
> Rebasing Docker images on `scratch` instead of alpine

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- hooks/build
- hooks/post_push
A bunch of stuff here...
- doing `build-release` as a Docker build so I can control the version of Go being used
- can build multi-arch images by setting `OS` and `ARCH` build args (except Windows right now)
> Dockerizing the build-release target

- docs/content/installing.md
The command at https://gomplate.hairyhenderson.ca/installing/#use-with-docker missing a `-f` flag
> Fix the example command in 'use with docker' section

- strings/strings.go
- strings/strings_test.go
When recursively generating YAML, it is useful to have a simple generic template definition that starts with an indent of 0 and increments at each level YAML.  If you pass `width` of 0 to the function as it was before this change, it would indent it one level without complaining, which was a great source of confusion to me.
> strings.Indent should not indent when width is 0

- Gopkg.lock
- Gopkg.toml
- docs/content/functions/sockaddr.md
- funcs.go
- funcs/sockaddr.go
- test/integration/sockaddr_test.go
- vendor/github.com/hashicorp/go-sockaddr/LICENSE
- vendor/github.com/hashicorp/go-sockaddr/doc.go
- vendor/github.com/hashicorp/go-sockaddr/ifaddr.go
- vendor/github.com/hashicorp/go-sockaddr/ifaddrs.go
- vendor/github.com/hashicorp/go-sockaddr/ifattr.go
- vendor/github.com/hashicorp/go-sockaddr/ipaddr.go
- vendor/github.com/hashicorp/go-sockaddr/ipaddrs.go
- vendor/github.com/hashicorp/go-sockaddr/ipv4addr.go
- vendor/github.com/hashicorp/go-sockaddr/ipv6addr.go
- vendor/github.com/hashicorp/go-sockaddr/rfc.go
- vendor/github.com/hashicorp/go-sockaddr/route_info.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_bsd.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_default.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_linux.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_solaris.go
- vendor/github.com/hashicorp/go-sockaddr/route_info_windows.go
- vendor/github.com/hashicorp/go-sockaddr/sockaddr.go
- vendor/github.com/hashicorp/go-sockaddr/sockaddrs.go
- vendor/github.com/hashicorp/go-sockaddr/template/doc.go
- vendor/github.com/hashicorp/go-sockaddr/template/template.go
- vendor/github.com/hashicorp/go-sockaddr/unixsock.go
Fixes #145 
Adds a pile of functions from the [`go-sockaddr`](https://github.com/hashicorp/go-sockaddr) package:
- `sockaddr.GetAllInterfaces`
- `sockaddr.GetDefaultInterfaces`
- `sockaddr.GetPrivateInterfaces`
- `sockaddr.GetPublicInterfaces`
- `sockaddr.Sort`
- `sockaddr.Exclude`
- `sockaddr.Include`
- `sockaddr.Attr`
- `sockaddr.Join`
- `sockaddr.Limit`
- `sockaddr.Offset`
- `sockaddr.Unique`
- `sockaddr.Math`
- `sockaddr.GetPrivateIP`
- `sockaddr.GetPrivateIPs`
- `sockaddr.GetPublicIP`
- `sockaddr.GetPublicIPs`
- `sockaddr.GetInterfaceIP`
- `sockaddr.GetInterfaceIPs`
I tried to closely match the function names that are exported in [github.com/hashicorp/go-sockaddr/template](https://github.com/hashicorp/go-sockaddr/tree/master/template), though couldn't directly import the `FuncMap`s …
> Adding sockaddr namespace

- Makefile
This pull request enables release builds for FreeBSD on amd64 - my test shows that all is well building, so I don't think any other modifications need to be made!
> meta: Add release for freebsd-amd64

- funcs/base64.go
- funcs/conv.go
- funcs/data.go
- funcs/env.go
- funcs/file.go
- funcs/net.go
- funcs/regexp.go
- funcs/strings.go
- funcs/time.go
- gomplate_test.go
This relaxes the input types required for many functions where previously a `string` or `int64` was explicitly required. This is mainly for the use-case where functions need to be able to participate in a pipeline that doesn't produce exactly the right input.
This will now work, for example:
```console
$ gomplate -i '{{ conv.Bool 1 }} {{ time.Second "15" }}'
true 15s
```
> Relax inputs for many functions

- docs/content/functions/time.md
- funcs/time.go
Rounding out `time` a bit with a new `time.ParseDuration` wrapper.
> Adding time.ParseDuration function

- docs/content/functions/conv.md
- funcs/conv.go
- funcs/conv_test.go
Fixes #213 
Note that this will _not_ fix the case where the input is undefined (i.e. referencing things like `.foo` where there is no `foo` field of `.`), but `conv.Has` can still be used for that.
> Adding new conv.Default function

- gomplate_test.go
- template.go
- template_test.go
For when gomplate is used programatically.
> Exporting the writer used when templates are sent to Stdout

- gomplate.go
- gomplate_test.go
- metrics.go
This isn't (currently) used in gomplate itself, but I'd like to report this sort of information in tools that call gomplate programmatically.
This is intended to be an unstable API right now, so I'll be considering changes to this as automatically non-breaking.
> Adding basic metrics around template rendering

- gomplate.go
Now that gomplate can more easily be called programmatically, we need to make sure it doesn't close `os.Stdout`!
> Avoid closing stdout

- cmd/gomplate/main.go
- docs/content/usage.md
- test/integration/basic_test.go
> Execute additional command after --

- data/datasource.go
- data/datasource_awssmp.go
- data/datasource_awssmp_test.go
- data/datasource_test.go
- gomplate.go
Errors involving datasources (such as a missing or empty datasource) result in gomplate exiting with a message with little context. This improves the situation, as well removes (almost) the use of `log.Fatal`/`log.Fatalf`.
A few function signatures change (added `error` return value), but they're mostly intended for use in templates, where an `error` is OK (and handled by `text/template`).
> Improving error handling for datasources

- data/datasource.go
- data/datasource_test.go
- test/integration/datasources_vault_test.go
Back when #200 was fixed (in #201), the assumption was made that if the data from the datasource was empty (i.e. an empty `[]byte`), then this was an error condition and gomplate should effectively stop processing the datasource.
It turns out that this was actually a regression, and there are valid scenarios for having empty datasources - maybe a file is empty, and _should_ be able to be parsed (like in #311).
I've re-thought this approach, and instead of being so heavy-handed, I'll allow empty datasources. In the specific Vault case (from #200), I'll simply return an `error` like I should've in the first place!
> Relaxing restriction on empty datasources

- Makefile
Fixes #318 
The next release of gomplate will have `checksums.txt` and `checksums.txt.signed` available for verifying the binaries.
Note: to verify the signed file, `keybase verify < checksums.txt.signed` - should confirm that I ([dhenderson](https://keybase.io/dhenderson) on [keybase](https://keybase.io/)) created the checksums file, and therefore built and uploaded the binaries.
> Add ability to generate checksums of binaries

- docs/content/functions/strings.md
- funcs/strings.go
- test/integration/strings_test.go
Wrapping two more functions from `strings`.
Had to adapt `strings.Repeat` a bit so that it won't panic!
> Adding strings.TrimSuffix and strings.Repeat

- docs/content/installing.md
> Improving documentation around slim binaries

- docs/content/functions/sockaddr.md
This commit removes any mention of the "private" selector from the Include and
Exclude filters, as it is not supported by the upstream `go-sockaddr` project.
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
> Remove notion of "private" selector from the Include/Exclude filter.

- docs/content/functions/sockaddr.md
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
> Add missing anchor for RFC 1918 link in sockaddr documentation.

- docs/content/functions/math.md
- funcs/math.go
- funcs/math_test.go
- test/integration/math_test.go
More functions in the `math` namespace:
- `math.Abs`
- `math.IsInt`
- `math.IsFloat`
- `math.IsNum`
- `math.Max`
- `math.Min`
- `math.Ceil`
- `math.Floor`
- `math.Round`
Most other functions now also support floating-point arithmetic if at least one of the inputs is a float.
Plus, all functions return an `interface{}` instead of an explicit `int64` (or `float64`).
> Adding more math functions

- data/datasource.go
- data/datasource_file.go
- data/datasource_file_test.go
- data/datasource_test.go
- data/datasource_vault.go
- data/datasource_vault_test.go
- data/mimetypes.go
- docs/content/datasources.md
- test/integration/datasources_file_test.go
Fixes #215, supersedes #124.
Unlike previous proposals, this does not read all files in the directory first. The semantics are the same as for #332 in that it just returns an array of the file names in the directory, which can then be iterated and read with further `datasource` function calls.
> Adding directory support for file datasources

- data/datasource_env.go
- data/datasource_env_test.go
- data/datasource_file_test.go
- docs/content/datasources.md
- test/integration/datasources_env_test.go
A simple `env` datasource, mostly for test/dev. Could support directory semantics - `env:/` could return an array of all variable names, or `env:///FOO_/` could list vars with the prefix `FOO_`, or maybe glob semantics could be added instead (`env:FOO_*`). For now, this is just simple direct references.
> Adding env datasource

- conv/conv.go
- conv/conv_test.go
Numbers with commas as thousands-separators like `"4,096"` are converted to `0`:
```console
$ gomplate -i '{{ conv.ToFloat64 "4,096" }}'
0
```
This PR fixes it!
> Support commas in number conversion

- conv/conv.go
- docs/content/functions/conv.md
- funcs/conv.go
New `conv.ToStrings` function to convert an array of things to an array of strings...
> Add conv.ToStrings function

- docs/content/functions/filepath.md
- docs/content/functions/path.md
- funcs.go
- funcs/filepath.go
- funcs/filepath_test.go
- funcs/filepath_windows_test.go
- funcs/path.go
- funcs/path_test.go
Adds a bunch of new functions in 2 related namespaces: `path` and `filepath`. These mostly expose Go's [path](https://golang.org/pkg/path/) and [path/filepath](https://golang.org/pkg/path/filepath/) packages:
- `path.Base`
- `path.Clean`
- `path.Dir`
- `path.Ext`
- `path.IsAbs`
- `path.Join`
- `path.Match`
- `path.Split`
- `filepath.Base`
- `filepath.Clean`
- `filepath.Dir`
- `filepath.Ext`
- `filepath.FromSlash`
- `filepath.IsAbs`
- `filepath.Join`
- `filepath.Match`
- `filepath.Rel`
- `filepath.Split`
- `filepath.ToSlash`
- `filepath.VolumeName`
> New path/filepath function namespaces

- data/datasource.go
- data/datasource_test.go
- docs/content/datasources.md
- docs/content/functions/data.md
- funcs/data.go
- test/integration/datasources_file_test.go
- test/integration/datasources_http_test.go
Adds a new function `defineDatasource` that acts the same way as the `--datasource` commandline flag, useful for defining default datasource URLs in templates.
See also #349.
> Adding new defineDatasource function

- data/datasource.go
- data/datasource_test.go
The original implementation of #356 allowed an empty alias. This doesn't really make sense, so I'm disallowing it.
Also changing function signature so errors are properly propagated.
> Require alias for defineDatasource

- data/datasource.go
- data/datasource_test.go
- docs/content/functions/data.md
- test/integration/datasources_http_test.go
Fixes #349 
Allows `datasource`/`ds` to be given a URL instead of an alias, for situations (like when ranging through a directory datasource) when the URL either can't be known in advance, or is awkward to specify in advance.
Behind the scenes, a new datasource is created dynamically, with the URL as the alias. This means the data is cached for multiple uses.
Note that the URL _must_ be an absolute URL in this case.
> Allowing datasources to be defined dynamically

- docs/content/functions/test.md
- funcs.go
- funcs/aws_test.go
- funcs/test.go
- test/test.go
- test/test_test.go
New namespace `test` with two functions for now:
- `test.Assert` (or `assert`): assert some condition to be true, or fail template generation
- `test.Fail` (or `fail`): fail template generation immediately
> Adding fail and assert functions

- cmd/gomplate/main.go
- tests/integration/basic_test.go
- tests/integration/inputdir_test.go
- tests/integration/strings_test.go
This makes gomplate a little less noisy when there's an error during template rendering, as opposed to commandline parsing or setup errors.
Now, instead of printing the usage message and the error message twice (top and bottom), it'll just print the error once:
```
$ gomplate -i '{{ foo }}'
template: <arg>:1: function "foo" not defined
```
In the case of errors during function calls (like `fail`, for example), it's a bit more verbose:
```
$ gomplate -i '{{ fail }}'
template: <arg>:1:3: executing "<arg>" at <fail>: error calling fail: template generation failed
```
When providing a bogus commandline flag, the behaviour will remain the same:
```
$ gomplate --blargh
Error: unknown flag: --blargh
Usage:
gomplate [flags]
Flags:
-d, --datasource datasource      datasource in alias=URL form. …
```
> Reducing output on template errors

- conv/conv.go
- conv/conv_test.go
- docs/content/functions/conv.md
Teaching `has`/`conv.Has` to look for values in slices/arrays as well as maps.
Also expands map key support to handle any key type, not just `string`s.
> Adding slice/array support to conv.Has

- Makefile
- docs-src/content/functions/conv.yml
- docs-src/content/functions/filepath.yml
- docs-src/content/functions/func_doc.md.tmpl
- docs-src/content/functions/math.yml
- docs-src/content/functions/path.yml
- docs-src/content/functions/strings.yml
- docs-src/content/functions/test.yml
- docs/content/functions/filepath.md
- docs/content/functions/math.md
- docs/content/functions/path.md
- docs/content/functions/test.md
This is _the beginning_ of an idea to generate the doc markdown in a more uniform way.
I have a vague awareness that Hugo (which I use for generating the doc site) may support something similar, but I don't know how it works, and I think I may be able to eventually generate other formats of docs (such as some man pages, as in #151?) from this...
At the very least, it'll help clean up the differences in formatting, and will probably give me a kick in the pants to better-document some of the older functions.
> Generating docs

- data/datasource.go
- data/datasource_test.go
- docs/content/datasources.md
- tests/integration/datasources_http_test.go
- tests/integration/integration_test.go
Fixes #370, closes #373 
This defers the mime type calculation until it's actually necessary. I've also severely simplified (and eliminated uses of) `NewSource`. It can be deprecated/removed later. Also I've noticed that `Ext` and `Params` aren't used at all, and contain info that can be easily calculated from the URL. And most (all?) of the properties of the `Source` struct should be unexported. But those things can (will!) happen in a followup PR.
> Fixing MIME type precedence

- docs/content/installing.md
Fixes #386
Tested this out in a clean `golang:1.11` container:
```console
$ docker run -it --rm golang:1.11 sh -c 'go get github.com/hairyhenderson/gomplate/cmd/gomplate && gomplate -h'
Process text files with Go templates
Usage:
gomplate [flags]
Flags:
...
```
> Fixing install instructions for go get

- docs-src/content/functions/conv.yml
- docs-src/content/functions/func_doc.md.tmpl
- docs/content/functions/conv.md
> Improve docs for conv namespace

- cmd/gomplate/main.go
- gomplate.go
- template.go
- template_test.go
Does this seem like a good approach for loading additional templates like `{{ template "otherfile.tpl" }}`?
I think couldn't think what to call the CLI arg - maybe `--additional-templates` is better, but here's a straw man.
Cheers, great project, just this one thing missing IMO :+1: :100: :heart:
> new arg --templates for parsing additional templates

- docs-src/content/functions/other.yml
- docs/content/functions/other.md
- gomplate.go
- template.go
- tests/integration/tpl_test.go
- tpl_func.go
- tpl_func_test.go
Fixes #419 
Adds a `tpl` function for doing templating in-line.
Can be called 4 ways:
- `{{ tpl "inline template" }}` - unnamed (single-use) template with default context
- `{{ tpl "name" "inline template" }}` - named template with default context
- `{{ tpl "inline template" $foo }}` - unnamed (single-use) template with given context
- `{{ tpl "name" "inline template" $foo }}` - named template with given context
When given a name, templates can be reused with the `template` keyword:
```console
$ gomplate -i '{{ tpl "foo" "inline template" }} {{ template "foo" }}'
inline template inline template
```
> New tpl function

- cmd/gomplate/main.go
- context.go
- context_test.go
- data/datasource.go
- docs/content/datasources.md
- docs/content/syntax.md
- docs/content/usage.md
- gomplate.go
- tests/integration/datasources_file_test.go
Fixes #404 
Adds a new `--context`/`-c` commandline flag to allow pre-loading a datasource into the template's context.
This allows this sort of usage:
```console
$ gomplate -c foo=https://example.com/foo.json -c bar.yml -i '{{ .foo.value }}, {{ .bar.value }}'
foo's value, bar's value
$ gomplate -c .=baz.yml -i '{{ .value }}'
baz's value
```
Caveats:
- all context datasources are loaded first - this can introduce latency
- setting the root (with alias of `.`) makes `.Env` unavailable
- sub-paths can't be given to context datasources in the template (i.e. `{{ datasource "foo" "subpath" }}`)
- inline datasources can't be added to the context at runtime
Other:
- context datasources are still available by name as regular datasources:
```console
$ gomplate -c .=baz.yml -i '{{ .value }} - {{ …
```
> New --context flag for pre-loading datasources into context

- docs-src/content/functions/test.yml
- docs/content/functions/test.md
- funcs/test.go
- funcs/test_test.go
Fixes #428 
Note that this differs slightly from the sprig version - the third arg is not required to be a `bool`.
> New test.Ternary function

- docs-src/content/functions/regexp.yml
- docs/content/functions/regexp.md
- funcs/regexp.go
- funcs/regexp_test.go
- regexp/regexp.go
- regexp/regexp_test.go
✨
Four new functions in the `regexp` namespace:
- `regexp.Find` - returns first match
- `regexp.FindAll` - returns all, or _n_ matches
- `regexp.ReplaceLiteral` - same as `regexp.Replace`, except treats replacement string literally (no variables)
- `regexp.Split` - same as `strings.Split`, but matches separators with regular expressions
> Adding more regexp functions

- docs/content/usage.md
- template.go
- template_test.go
- tests/integration/basic_test.go
Fixes #430 
This adds a new environment variable `GOMPLATE_SUPPRESS_EMPTY` which, if set to `true`, will cause output files to not be created if the template only outputs whitespace.
> Adding option to suppress empty output files

- data/datasource.go
- data/datasource_http.go
- data/datasource_http_test.go
- data/datasource_test.go
- tests/integration/datasources_http_test.go
I thought I could provide a second argument to `datasource` to build on the URL for HTTP datasources:
```
gomplate -d d=http://example.com/ -i '{{ datasource "d" "foo/bar/baz" }}'
```
Which should effectively access `http://example.com/foo/bar/baz`.
But, it didn't work!
Now, with this PR, it does.
This also splits the http datasource code into a separate file (`datasource.go` is getting a mite large)
> Support subpaths for http datasources

- docs/content/syntax.md
I found myself writing multi-line action blocks to improve readability but could not understand why each action left a newline behind. Because I was running this in Docker Compose, I didn't want to alter the `ENTRYPOINT` to your image to do some data munging with `bash` to workaround it.
I saw that some example code in your documentation had leading and trailing minus signs after and before the action delimiters. I figured this was worth something, so I used it in my code and discovered that this is how you suppress newlines.
While this is well-known for those that use Go templates, it wasn't clear to this not-yet-a-Golang dev. I added some documentation to explain this better for folks like me.
I love this tool! Thank you for making it!
> Document suppressing newlines.

- aws/ec2info.go
- aws/ec2info_test.go
- aws/ec2meta.go
Fixes #458 by always looking up the region when creating a new `SDKSession`
> AWS region detection for SSM param store datasources

- conv/conv.go
- conv/conv_test.go
- docs-src/content/functions/conv.yml
- docs/content/functions/conv.md
- funcs/conv.go
Related to #467 
Adding two new functions `conv.Keys` and `conv.Values`, also aliased as `keys` and `values`.
> New functions conv.Keys and conv.Values

- Gopkg.lock
- coll/coll.go
- coll/coll_test.go
- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
- funcs/coll.go
- tests/integration/collection_test.go
- vendor/github.com/imdario/mergo/LICENSE
- vendor/github.com/imdario/mergo/doc.go
- vendor/github.com/imdario/mergo/map.go
- vendor/github.com/imdario/mergo/merge.go
- vendor/github.com/imdario/mergo/mergo.go
- vendor/github.com/imdario/mergo/testdata/license.yml
Adding a new `coll.Merge` (or `merge`) function. This just wraps the `github.com/imdario/mergo` package, just like Sprig's `merge`.
Relates to #467 
> New coll.Merge function

- data/datasource.go
- data/datasource_env.go
- data/datasource_merge.go
- data/datasource_merge_test.go
- data/datasource_test.go
- docs/content/datasources.md
- tests/integration/datasources_merge_test.go
Fixes #467 
This adds a new meta-datasource with the scheme `merge:`.
See this comment for details: https://github.com/hairyhenderson/gomplate/issues/467#issuecomment-457983206
> New merge datasource, for merging multiple datasources

- docs/content/functions/file.md
- file/file.go
- file/file_test.go
- funcs/file.go
- tests/integration/file_test.go
Addresses part of #485.
This will only write to files _inside_ the current working directory, for safety. It will, however, overwrite existing files, so _caveat emptor_.
> New file.Write function

- docs-src/content/functions/tmpl.yml
- docs/content/functions/tmpl.md
- template.go
- tests/integration/tmpl_test.go
- tmpl/tmpl.go
- tmpl/tmpl_test.go
As a bit of a precursor to #444 and #485, I'm creating a new `tmpl` namespace (I considered `templates`, but `tmpl` seems better). I'm moving the `tpl` function into `tmpl.Inline`, and making `tpl` an alias to that.
This gets added in a bit of a different way (outside of the `Funcs` func), because it needs to be added a bit later on and with extra info.
This also marks the end of the short-lived `Other functions` doc section, _for now..._ 
> New tmpl namespace & move tpl function to tmpl.Inline

- docs-src/content/functions/tmpl.yml
- docs/content/functions/tmpl.md
- tests/integration/tmpl_test.go
- tmpl/tmpl.go
- tmpl/tmpl_test.go
Fixes #444 
Fixes #485 
This is basically the same as `template`, except it outputs a string.
> New tmpl.Exec function

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- funcs/strings.go
- strings/strings.go
- strings/strings_test.go
- tests/integration/strings_test.go
I've wanted a way to do word-wrapping/line-breaking for a while, so here's a start. I'm not 100% satisfied with this, mostly because it doesn't properly handle multi-byte runes or non-whitespace line-break opportunities (especially in non-alphabetic languages). But at the risk of letting the _perfect_ get in the way of the _good enough,_ here it is.
It uses the same package that Sprig's `wrap` uses (`github.com/Masterminds/goutils`), which is about as good as it gets in terms of Go word-wrapping packages (that I could find, at least!). Perhaps _some day_ I'll submit some enhancements to handle the use-cases I'm looking for.  https://godoc.org/github.com/gorilla/i18n/linebreak may be of some help as well.
For now, the function takes 1, 2, or 3 args, to customize the width and/or the …
> New strings.WordWrap function

- docs-src/content/functions/aws.yml
- docs-src/content/functions/base64.yml
- docs-src/content/functions/crypto.yml
- docs-src/content/functions/data.yml
- docs-src/content/functions/env.yml
- docs-src/content/functions/func_doc.md.tmpl
- docs-src/content/functions/math.yml
- docs-src/content/functions/net.yml
- docs-src/content/functions/path.yml
- docs-src/content/functions/sockaddr.yml
- docs-src/content/functions/strings.yml
- docs-src/content/functions/time.yml
- docs/content/functions/aws.md
- docs/content/functions/base64.md
- docs/content/functions/coll.md
- docs/content/functions/conv.md
- docs/content/functions/crypto.md
- docs/content/functions/data.md
- docs/content/functions/env.md
- docs/content/functions/file.md
- docs/content/functions/filepath.md
- docs/content/functions/math.md
- docs/content/functions/net.md
- docs/content/functions/path.md
- docs/content/functions/regexp.md
- docs/content/functions/sockaddr.md
- docs/content/functions/strings.md
- docs/content/functions/test.md
- docs/content/functions/time.md
- docs/content/functions/tmpl.md
Just finishing the job I started too long ago... 😉
This aims for the least number of differences while also bringing all the function docs in-line with the standard format.
> docs: YAMLifying the rest of the function docs, improving the doc template

- data/data.go
- data/data_test.go
- tests/integration/datasources_merge_test.go
Fixes #509 - had to adapt the `map[string]string` returned by `godotenv.Unmarshal` to a `map[string]interface{}` like all the other parsers!
> Fix .env file parsing so merging works properly

- file/file.go
- file/file_test.go
> file.Write should truncate existing files

- docs-src/content/functions/random.yml
- docs/content/functions/random.md
- funcs.go
- funcs/random.go
- funcs/random_test.go
- random/random.go
- random/random_test.go
Fixes #487 
Introduces the `random` namespace, with these functions:
- `random.ASCII`
- `random.Alpha`
- `random.AlphaNum`
- `random.String`
- `random.Item`
- `random.Number`
- `random.Float`
> New random namespace for generating random strings and numbers

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- funcs/strings.go
- funcs/strings_test.go
New `strings.RuneCount` function, properly character-count for strings involving multi-byte code-points.
> Adding strings.RuneCount function

- docs/content/installing.md
Fixes #519
Now that https://github.com/gomplate/gomplate-npm is active (mostly), gomplate can be installed with:
```console
$ npm install -g gomplate
```
> gomplate can also be installed with npm

- Gopkg.lock
- Gopkg.toml
- Makefile
- appveyor.yml
- data/datasource.go
- data/datasource_awssmp_test.go
- data/datasource_env_test.go
- data/datasource_file_test.go
- data/datasource_merge_test.go
- data/datasource_test.go
- docs/content/usage.md
- template_test.go
- template_unix_test.go
- template_windows_test.go
- tests/integration/basic_nonwindows_test.go
- tests/integration/basic_test.go
- tests/integration/collection_test.go
- tests/integration/datasources_boltdb_test.go
- tests/integration/datasources_file_test.go
- tests/integration/datasources_http_test.go
- tests/integration/datasources_merge_test.go
- tests/integration/file_test.go
- tests/integration/gomplateignore_test.go
- tests/integration/inputdir_test.go
- tests/integration/time_test.go
- tests/integration/tmpl_test.go
- vendor/github.com/zealic/xignore/pattern.go
Having a bit of a Windows-bug-fixing marathon this weekend. The goal is to get as many of the unit & integration tests passing on Windows, and also to fix #505.
What this does:
- handles Windows drive letters correctly as part of URLs (i.e. `file:///C:/foo/bar` is correctly parsed as the path `C:\foo\bar` instead of `\C:\foo\bar`
- this makes datasources work (which fixes #505)
- upgrades `github.com/zealic/xignore` to v0.3.3
- this fixes `.gomplateignore` and `--exclude` support on Windows
- accepts the fact that `os.Chmod` doesn't really work on Windows (well, it _does_, just not the way it works on UNIX, and not in any useful way for our purposes)
- docs updated to reflect this
- ignores some tests because Windows has no support for the `TZ` environment variable
- enables a pile of …
> Some more Windows fixes

- aws/sts.go
- aws/sts_test.go
- aws/testutils.go
- docs-src/content/functions/aws.yml
- docs/content/functions/aws.md
- funcs/aws.go
Adding 3 new functions that wrap the AWS STS `GetCallerIdentity` API:
- `aws.Account`
- `aws.UserID`
- `aws.ARN`
These all answer various facets of "who am I?"
> AWS STS functions

- config.go
- config_test.go
- gomplate.go
- gomplate_test.go
- template.go
- template_test.go
Refactoring the `gomplate.Config` struct, and adding a `defaults()` function that helps bring some sanity to code that uses it (not so much need for protecting against situations which should never happen).
> Refactor Config

- cmd/gomplate/main.go
- cmd/gomplate/main_test.go
- config.go
- config_test.go
- docs/content/usage.md
- gomplate.go
- gomplate_test.go
- template.go
- template_test.go
- template_unix_test.go
- template_windows_test.go
- tests/integration/basic_test.go
- tests/integration/inputdir_test.go
Fixes #288 
Adds a new `--output-map` argument, which can be used instead of `--output-dir` to map provide a "mapping template" for choosing what to name each output file.
> Adding --output-map argument for templating output paths

- Makefile
- aws/kms.go
- cmd/gomplate/main.go
- config.go
- data/data.go
- data/datasource_file_test.go
- data/datasource_http_test.go
- data/datasource_test.go
- data/datasource_vault.go
- env/env_test.go
- funcs/math.go
- funcs/uuid_test.go
- gomplate.go
- math/math.go
- random/random.go
- template.go
- template_test.go
- tests/integration/basic_test.go
- tests/integration/datasources_consul_test.go
> chore: Switch from gometalinter to golangci-lint

- Dockerfile
- Makefile
- cmd/gomplate/main.go
- hooks/build
- version/version.go
This makes the build _slightly_ more reproducible (see https://reproducible-builds.org/docs/timestamps/).
> Removing BuildDate to make build more reproducible

- cmd/gomplate/main.go
- cmd/gomplate/main_test.go
- docs/content/usage.md
- tests/integration/gomplateignore_test.go
Fixes #540.
`--include` is effectively the inverse of `--exclude`, with an implicit `--exclude '*'` to start. But `--include` is a bit easier to reason about 😉
> Adding --include flag

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- funcs/strings.go
- funcs/strings_test.go
- strings/strings.go
- strings/strings_test.go
As discussed in #584. Ended up implementing inline as I don't trust the regex-based approach to deciding which strings need to be quoted to be safe for all possible extended shells.
> Implement shell-compatible quoting

- funcs/crypto.go
Apparently `stylecheck` now cares about this too 🤷‍♂
> Ignore new lint failures

- data/datasource.go
- data/datasource_test.go
- tests/integration/datasources_http_test.go
Fixing a paper cut I've been meaning to for a while 😂
Some composite MIME types can have `+`s in them, for example `application/array+json`. So when overriding in the URL with the `type` param, you get `http://example.com/list?type=application/array+json`, and the `+` character decodes to ` ` (space).
This breaks mime parsing, so I'm fixing it to assume the ` ` can get replaced with a `+`. An encoded `+` (`%2B`) always worked - that's what I've used until now.
Also improving error handling so MIME parsing failures are a bit more obvious. And more tests!
> Fix parsing of media types with + character

- coll/coll.go
- conv/conv.go
- funcs/random.go
- internal/conv/conv.go
- internal/conv/conv_test.go
`interfaceSlice` was copy/pasted a whole bunch, and it had some (very mild) performance inefficiencies. This moves it into an internally-exported package, makes things ever-so-slightly faster & reduces allocations.
> Slight performance improvement & refactoring

- docs/content/usage.md
Placed a (missing) newline before the start of a list so it renders the list good.
Currently shown as:
> Placed a newline before the start of a list

- cmd/gomplate/main.go
- config.go
- docs/content/usage.md
- go.sum
- gomplate.go
- plugins.go
- plugins_test.go
- tests/integration/plugins_test.go
- tests/integration/plugins_windows_test.go
Fixes #580 
Implements a new `--plugin` command line flag. It's a pretty straightforward feature - just adds new functions on the command line that will cause external processes to be run. Stdout is rendered 
into the template, and Stderr is passed through to the main Stderr. Arguments are passed through as positional args to the given process.
Scripts are also supported on all OSes, including Powershell (`.ps1`) and CMD (`.cmd` and `.bat`) scripts (on Windows), where the `powershell` or `pwsh` or `cmd.exe` command will be used.
> Plugins for custom functions

- cmd/gomplate/main.go
- cmd/gomplate/validate.go
- cmd/gomplate/validate_test.go
- config.go
- docs/content/usage.md
- gomplate_test.go
- template.go
- tests/integration/basic_test.go
New `--exec-pipe` option which redirects output to the post-run exec command's stdin.
Fixes #581 
Currently, only a single input is supported. If there's demand later on, we could discuss use-cases...
> New --exec-pipe output option

- .github/workflows/windows.yml
- Makefile
- tests/integration/integration_test.go
It's behaving weird all of a sudden: https://github.com/hairyhenderson/gomplate/pull/649/checks?check_run_id=274161463
Let's see if `make test` works on the GitHub Actions windows workers!
> Fix windows build

- hooks/build
- hooks/post_push
Fixes #648
Produces 6 new tags for the [hairyhenderson/gomplate](https://hub.docker.com/r/hairyhenderson/gomplate) image:
- `stable`, `v3` (currently equal to `v3.5.0`)
- `stable-slim`, `v3-slim` (currently equal to `v3.5.0-slim`)
- `stable-alpine`, `v3-alpine` (currently equal to `v3.5.0-alpine`)
> Tag stable and major docker images

- data/datasource.go
- data/datasource_file_test.go
- data/datasource_merge.go
- data/datasource_test.go
- tests/integration/datasources_file_test.go
> Fix bug where subpath was ignored when inferring MIME type

- data/data.go
- data/data_test.go
This relates to #534, and while full multi-document stream support is going to take a bit longer to fully figure out, I think this is a quick win.
Basically this handles the (not uncomment in Helm and Kubernetes-land) case where a file like:
```yaml
---
foo: bar
```
will get parsed by gomplate as just a single `nil`, which is pretty much never what we _actually_ want.
So now YAML will ignore non-empty documents and return the first one in the stream.
> Return first non-empty YAML document when parsing YAML streams

- vault/auth.go
Mild refactoring - Go 1.12 introduced `os.UserHomeDir`, which is slightly better than my `homeDir()` function here!
> Remove unnecessary homeDir function

- .github/workflows/build.yml
- .github/workflows/docker.yml
`actions/checkout` has recently bumped to v2 (beta) in `master`, which breaks some stuff. Pinning to `v1`.
> pin actions/checkout action to v1

- docs/content/datasources.md
> Documentation for the gs datasource scheme

- data/datasource.go
- data/mimetypes.go
- data/mimetypes_test.go
Fixes #738 
I also added `application/text` as an alias to `text/plain`, as it was mentioned in the same Slack conversation that triggered #738...
> Adding a few MIME type aliases

- cmd/gomplate/logger.go
- cmd/gomplate/main.go
- go.mod
- go.sum
- gomplate.go
- gomplate_test.go
- plugins.go
- plugins_test.go
- tests/integration/inputdir_test.go
- tests/integration/tmpl_test.go
Starting initial work on propagating `context.Context` throughout gomplate for cleaner cancellation/timeout/etc support, and instead of just using `fmt.Fprintf` for logging, switching to `zerolog`. This has the added benefit that I can now do some verbose logging in "deeper" areas more easily.
Introduces a new `gomplate.RunTemplatesWithContext` function. Not sure I like the name, and I am likely to change the signature in #692.
> Adding context.Context support and a logger

- cmd/gomplate/main.go
- go.mod
- go.sum
Saves a bit of effort. Cobra currently only adds a `--version` flag and not a `-v` flag, though I've issued a PR spf13/cobra#996 to solve that. If/when that's merged/released, I'll bring this PR out of draft mode. I don't want to break the command, even for a non-critical flag like this.
(also the integration tests will break until that fix is in)
> Use cobra's built-in --version flag instead of implementing separately

- data/data.go
- data/data_test.go
- tests/integration/docs_examples_test.go
Fixes #804 
Slices are a bit of a pain in Go (`[][]interface{}` is not an `[]interface{}`, and `[]interface{}` is not an `interface{}`)...
This should cover the majority of the use-cases, though it won't handle `[]interface{}`s that contain different types of slices (something like `[]interface{}{[]string{"first", "second", "third"},[]interface{}{1, "2", 3}}` won't work). I'm not sure how common that would be, and certainly wouldn't be something that YAML or JSON parsing would create. If anyone runs into that kind of data structure, I can obviously add it though!
> Allow data.ToCSV to handle more general input types

- .github/workflows/docker.yml
- Dockerfile
- Makefile
> Produce multi-platform Docker images

- Dockerfile
Accidentally moved `/bin/gomplate` to `/gomplate` in #811 😅 
It's a bit odd because every other image has it in `/gomplate`. 🤷‍♂️ 
> Fix alpine docker image binary location

- .github/workflows/docker.yml
- Makefile
In #811 I didn't realize that the `docker pull` was only pulling down the `linux-amd64` image from the temporary local registry, so the pushed images weren't actually multi-arch...
This fixes it by using `docker buildx imagetools create` instead to do a carbon-copy of the images.
> Push all multi-arch docker images

- data/datasource.go
- data/datasource_test.go
- tests/integration/datasources_file_test.go
Fixes #809
Turns out paths passed on the commandline would've also suffered from this bug - the query string on non-absolute URLs (i.e. file paths) wasn't getting parsed.
So this wouldn't have been recognized:
```console
$ gomplate -d foo=./foo?type=application/json ...
```
And neither would inline uses of `defineDatasource` (such as reported in #809):
```
{{- defineDatasource "env_file" ".env.staging?type=application/x-env" -}}
```
Incidentally, this also fixes an issue I've experienced before when trying to emulate reads from Vault with a local directory:
```console
$ gomplate -d secrets=./secret_dir/?type=application/json -i '{{ (ds "secrets" "some/key").value }}'
```
> Fix broken file datasource URL parsing (query string was ignored)

- aws/ec2info.go
Fixes #795
Turns out the issue was that the region is set to `"unknown"` (as a default from `aws.EC2Region`) and so the config object was initialized incorrectly, and the region from the config was being overridden.
I've tested this locally, and it works fine. Unfortunately this can't easily be unit tested due to how the AWS SDK works.
> Fix AWS Session unknown region bug

- internal/tests/integration/basic_nonwindows_test.go
- internal/tests/integration/basic_test.go
- template.go
If an output file already exists but is not able to be read or written by the user, gomplate will fail to open it even if the `--chmod` flag is given.
This is because the new mode is only applied after attempting to open the file.
This fixes that behaviour by applying the `--chmod` before opening the file.
> Apply --chmod before opening output file

- internal/writers/writers.go
- internal/writers/writers_test.go
- template.go
Fixes #752
This is a behaviour change, though I don't consider it major enough to count as "breaking".
Before this change, output files would be blindly truncated before any writes, meaning that even if the content is identical, the modification time will change and the file will seem to some other utilities as if the file has changed.
With this change, writes to output files will be buffered until a difference is detected. This means that if the output matches what's already in the output file, the file will not be modified.
In the case of the output file not existing, it will be created as before.
This does not apply to stdout.
> Defer writing until output differs

- data/datasource_awssmp.go
- data/datasource_awssmp_test.go
- docs/content/datasources.md
Fixes #427 (though not completely).
I think I'll add support for a `recursive=true` param to all of the datasources that support directory semantics (separately). _That'll_ Fix #427 in its entirety.
> Add directory datasource support to aws+smp

- data/datasource_merge_test.go
Found this wasn't really covered during some refactoring... 
> Add test for relative paths in merge datasources

- Makefile
- data/datasource.go
- data/datasource_http.go
- data/datasource_http_test.go
- data/datasource_merge.go
- data/datasource_test.go
- internal/config/configfile.go
- internal/config/configfile_test.go
Only real functional change is uses of `absFileURL` are replaced with `parseSourceURL` which I'm fairly certain is basically the same effect, except with a few added checks up-front which would be skipped in all cases where `absFileURL` would've been called.
Also marks `NewData` as deprecated.
> refactoring: deduplicating identical URL-parsing functions

- cmd/gomplate/main.go
- config.go
- context.go
- context_test.go
- data/datasource_test.go
- gomplate.go
- internal/config/configfile.go
- internal/config/configfile_test.go
Tying off a few loose ends with naming & deprecations before 3.7 goes out...
> Deprecate legacy config struct

- data/datasource_aws_sm.go
- data/datasource_aws_sm_test.go
- data/datasource_awssmp.go
- data/datasource_awssmp_test.go
- data/datasource_env.go
- data/datasource_vault.go
- docs/content/datasources.md
Fixes #868
Note that this fixes both `aws+sm` and the `aws+smp` datasources.
Allows referencing parameters/secrets that _don't_ start with `/`.
> Allow referencing aws+sm[p] keys that don't start with '/'

- conv/conv.go
- conv/conv_test.go
- crypto/rsa.go
- crypto/rsa_test.go
- docs-src/content/functions/base64.yml
- docs-src/content/functions/crypto.yml
- docs/content/functions/base64.md
- docs/content/functions/crypto.md
- funcs/base64.go
- funcs/base64_test.go
- funcs/crypto.go
- funcs/crypto_test.go
- internal/tests/integration/crypto_test.go
Fixes #800
Introduces 6 new functions:
- `crypto.RSAEncrypt`
- `crypto.RSADecrypt`
- `crypto.RSADecryptBytes`
- `crypto.RSAGenerateKey`
- `crypto.RSADerivePublicKey`
- `base64.DecodeBytes`
Also fixes a bug I found in `conv.ToString` where a `[]byte` isn't converted to a `string` correctly.
> New RSA crypto functions, and new base64.DecodeBytes function

- docs/content/installing.md
This has been wrong for a long time! Thanks to @mcarifio for stumbling on this and reporting the issue!
Fixes #894 
> Update misleading 'go get' install instructions

- docs-src/content/functions/aws.yml
- docs/content/functions/aws.md
While working on #891, I noticed that `AWS_META_ENDPOINT` is not documented for AWS functions - this pull request adds that documentation.
> Document `AWS_META_ENDPOINT`

- docs-src/content/functions/gcp.yml
- docs/content/functions/gcp.md
- funcs.go
- funcs/gcp.go
- gcp/meta.go
This commit adds a new namespace and function: `gcp.Meta`, which can be used to look up values from the GCP Instance Metadata service.
An example usage:
```
echo '{{ gcp.Meta "id" }}' | gomplate
```
This also supports paths, so usage like this works:
```
echo '{{ gcp.Meta "network-interfaces/0/ip" }}' | gomplate
```
I've added a new documentation page to cover the GCP namespace, but it's unclear whether I have missed a spot where this page needs adding to a layout or similar.
> Add gcp.Meta function, equivalent to aws.EC2Meta but for GCP

- docs-src/content/functions/test.yml
- docs/content/functions/test.md
- funcs/test.go
- funcs/test_test.go
Fixes #892 
I've decided to only add 2 functions - `kind` and `isKind`. I suggested in #892 that it may make sense to have more specific functions like `isMap`, `isString`, etc... but I think starting with a general `isKind` is probably good enough.
In addition to supporting all the Go type kinds, I've added a generic `number` that `isKind` will accept for the general cases where any kind of number will suffice.
> Add test.Kind/kind and test.IsKind/isKind functions

- aws/ec2info.go
- aws/ec2info_test.go
- docs-src/content/functions/aws.yml
- docs/content/functions/aws.md
- funcs/aws.go
This adds a function to get all the EC2 tags. It is useful when we don't know the full tag upfront, but know the prefix/suffix of it.
> Add EC2Tags function

- go.mod
- gomplate_test.go
- internal/iohelpers/readers.go
- internal/iohelpers/readers_test.go
- internal/iohelpers/writers.go
- internal/iohelpers/writers_test.go
- internal/tests/integration/inputdir_test.go
- internal/tests/integration/inputdir_unix_test.go
- template.go
- template_test.go
- template_unix.go
- template_windows.go
Fixes #928 
This should streamline resource usage a bunch, especially when templating directories with large numbers of files.
> Only open output files when necessary

- cmd/gomplate/main.go
- conv/conv.go
- funcs/random.go
- funcs/strings.go
- internal/tests/integration/strings_test.go
- internal/tests/integration/typeconv_test.go
- strings/strings.go
- strings/strings_test.go
- vault/auth.go
A few fixes for issues caught by the linter, including a bug where the main context would not be cancelled when gomplate errors.
> Fix bug where context cancellation doesn't have a chance to run on errors

- data/datasource_git.go
- data/datasource_git_test.go
- go.mod
- go.sum
The repo changed, and bumped to v5 (though no other substantive changes).
> Migrate from src-d/go-git to go-git/go-git

- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/cmd/main.go
- internal/config/configfile.go
- internal/tests/integration/basic_test.go
Fixes #1018
Ever since I added config file support the defaults on the command flags have effectively been only for documentation purposes. This fixes the handling of `GOMPLATE_LEFT_DELIM` and `GOMPLATE_RIGHT_DELIM`.
The integration tests for this only passed by fluke 🤦‍♂️. I've updated them, and added some extra unit tests too.
> Fix ignored left/right delim env vars

- internal/cmd/main.go
- internal/tests/integration/basic_test.go
Fixes #996 
I need to entirely remove gomplate's use of stdin/stdout/stderr except for at the edges, but until then this'll fix this annoying issue!
> Only print newline with console output

- internal/cmd/main.go
In #1039 it became possible to set a different output stream than `os.Stdout`. This changes the convenience-newline logic to only happen when `os.Stdout` is indeed the output stream.
> Only print newline to when outputting to os.Stdout

- aws/ec2info.go
- gcp/meta.go
- vault/auth.go
Most places that read environment variables used [`env.Getenv`](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v3/env#Getenv). Now, all of them do.
> Prefer env.Getenv to os.Getenv

- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/tests/integration/config_test.go
Both the integration test and unit test for this particular behaviour were broken 🤦‍♂️
The rules of precedence are flags, then config file entries, then finally falling back to environment variables.
> Fix precedence bug with L/R Delimiters

- internal/cmd/main.go
- internal/cmd/main_test.go
- plugins.go
- plugins_test.go
Found some race conditions while working on #1050. This was due to a goroutine being launched without any way for it to stop (other than receiving a signal).
> Fix race condition in signal handling

- time/time.go
Ran into this during #1050 - it's sometimes necessary to be able to change `$TZ`, and this helps with that!
> Support changing TZ env var in Zone functions

- README.md
- docs/content/_index.md
- docs/content/datasources.md
- go.mod
- go.sum
- internal/tests/integration/datasources_boltdb_test.go
Ran into some data races with BoltDB, but it's archived. Switching to the active etcd-io/bbolt fork. The `docker/libkv` package has a commit that switches to it too, but there's not yet a release tagged with it, so I'm flipping to `master`.
> Use etcd-io/bbolt fork instead of boltdb/bolt

- funcs/time.go
Followup to #1052 - Same deal but for `time.ParseLocal`
> Support changing TZ env var in ParseLocal function

- internal/cmd/main.go
- internal/config/configfile.go
- internal/iohelpers/writers.go
- internal/iohelpers/writers_test.go
- internal/tests/integration/basic_test.go
- internal/tests/integration/inputdir_test.go
- template.go
- template_test.go
Fixes #1057 
I've also simplified some of the internal API to stop wrapping io.Writers as io.WriteClosers when it's pretty much unnecessary. 
> Avoid outputting newline to console when using --input-dir

- gomplate.go
- internal/tests/inprocess-integration/inputdir_test.go
- internal/tests/integration/inputdir_test.go
- template.go
When using `--input-dir .`, gomplate fails with an error `lstat <some file>: file does not exist`. I'm still not entirely sure why this isn't working, but I believe it's a bug in `xignore` (I'll log a bug upstream at some point soon). The workaround is fairly straightforward though - just feed the absolute path instead for that specific case.
This came up in https://github.com/hairyhenderson/gomplate/issues/1081#issuecomment-787548173.
> Fix --input-dir=. bug

- internal/cmd/main.go
- internal/tests/integration/basic_test.go
Fixes #1075 and #1074 by removing the feature entirely.
Note that this will change the perceived output when gomplate is used interactively with a template that does not end in a newline. For example:
in bash:
```console
$ gomplate -i "hello world"
hello world$ 
```
in zsh:
```console
$ gomplate -i "hello world"
hello world%
$ 
```
Note that this does not affect the stdout stream, which was never modified. Only the stderr stream was modified (and is now no longer modified).
> Stop printing newline on stderr when outputting to stdout

- internal/tests/inprocess-integration/datasources_blob_test.go
- internal/tests/integration/datasources_blob_test.go
This only runs when it's authenticated, so it's probably been broken for a while... The URL is just obsolete.
> Fix GCS integration test

- internal/cmd/logger.go
> Stop emitting ANSI colour codes on Windows in unsupported terminals

- random/random.go
- random/random_test.go
Turns out only the `rand.*` functions are safe for concurrent use...
> Fix data race in random functions

- .github/workflows/build.yml
This'll hopefully make things work for Dependabot on builds like #1147 
> ci: Don't attempt to send codeclimate results when secret is unavailable

- Makefile
Fixes #1122 
Adds the ability to build a zip file containing just the gomplate binary at the root.
I'll add this to my (still internal) automated release process and in the next gomplate release a `gomplate_windows-amd64.zip` archive will be made available.
> Add make target for zip files containing the binary

- docs/content/installing.md
The current alias command : 
```
alias gomplate=docker run hairyhenderson/gomplate
```
leads to the following error message : 
```
-bash: alias: run: not found
-bash: alias: hairyhenderson/gomplate: not found
```
This one does the job : 
```
alias gomplate='docker run hairyhenderson/gomplate'
````
> Typo in alias > simple quotes required

- internal/tests/integration/datasources_vault_ec2_test.go
- internal/tests/integration/test_ec2_utils.go
Some of the changes in Go 1.17 were to the [`crypto/x509`](https://golang.org/doc/go1.17#crypto/x509) package, and I suspect the date is now verified more carefully.
This should fix failures like [this one](https://github.com/hairyhenderson/gomplate/runs/3508960837?check_suite_focus=true)
> Add NotBefore/NotAfter to test cert so integration tests pass

- crypto/rsa.go
- crypto/rsa_test.go
- docs-src/content/functions/crypto.yml
- docs/content/functions/crypto.md
- funcs/crypto_test.go
Enhances the security of the `crypto.RSAGenerateKey` function to require at least 2048 bits. See https://cwe.mitre.org/data/definitions/326.html for details
> crypto.RSAGenerateKey - Enforce key length of at least 2048 bits

- conv/conv.go
- docs-src/content/functions/conv.yml
- docs/content/functions/conv.md
Protecting against [CWE-190](https://cwe.mitre.org/data/definitions/190.html) and [CWE-681](https://cwe.mitre.org/data/definitions/681.html).
> conv.ToInt: return -1 instead of overflowing on 32-bit systems

- data/datasource_git.go
- data/datasource_git_test.go
- docs/content/datasources.md
- internal/tests/integration/datasources_git_test.go
Fixes #1049
This is a workaround for https://github.com/go-git/go-git/issues/249, as suggested in https://github.com/go-git/go-git/issues/249#issuecomment-772354474.
Ideally `go-git` would do this for me, but for now this is the best option.
I've altered the tests so that one of the test repos has a default branch of `main`, to verify the behaviour.
If for some reason the remote's branch can't be determined, the error will be logged but the datasource will continue to defer to `go-git`'s default.
> Support git repos with default branches other than "master"

- docs/content/functions/strings.md
Add additional examples to clarifiy typical use cases for strings.Split.
Resolves  https://github.com/hairyhenderson/gomplate/issues/1278
> Add strings.Split example to strings.md

- internal/tests/integration/datasources_consul_test.go
- internal/tests/integration/integration_test.go
Not sure why I didn't see these test errors in CI, but I'm seeing them locally.
```
* Unexpected response code: 410 (Endpoint /v1/acl/create for the legacy ACL system was removed in Consul 1.11.)
```
> Update integration test to work properly with Consul v.11+

- data/datasource_aws_sm.go
- data/datasource_aws_sm_test.go
- docs/content/datasources.md
> aws+sm datasource - support reading from SecretBinary when SecretString is not set

- docs-src/content/functions/time.yml
- docs/content/functions/time.md
I was going to add a separate `time.IsDST` function, but it's just as easy to call `time.Now.IsDST`. Adding an example to show how to use this.
> Add example of how to use Time.IsDST

- crypto/aes.go
- crypto/aes_test.go
- docs-src/content/functions/crypto.yml
- docs/content/functions/crypto.md
- funcs/crypto.go
- funcs/crypto_test.go
Fixes #1299 
Adds three new functions `crypto.EncryptAES`, `crypto.DecryptAES`, and `crypto.DecryptAESBytes`. These differ from the Helm/sprig `encryptAES` and `decryptAES` functions in that they don't base64-encode/decode. This can be useful for situations where other transformations are desired.
These support variable key lengths (128/192/256), defaulting to 256.
> New crypto.EncryptAES/DecryptAES functions

- docs-src/content/functions/crypto.yml
- docs/content/functions/crypto.md
- funcs/crypto.go
Sometimes it's useful to be able to get a SHA sum in a form other than hexadecimal, so this adds new functions for that.
> New crypto.SHA*Bytes functions

- docs/content/installing.md
- update `go get` instructions (deprecated, use `go install` instead)
- dropping mention of slim/UPX (no longer recommended due to bugs)
> Updating install docs

- funcs/strings.go
- funcs/strings_test.go
- internal/tests/integration/strings_test.go
There's a bug in Go's [`strings.Title`](https://pkg.go.dev/strings#Title) function which prevents it from recognizing words separated by certain unicode punctuation marks. In Go 1.18, `strings.Title` will be deprecated. This replaces that usage with `golang.org/x/text/cases`, as suggested by the Go 1.18 documentation.
I've also updated the `ToUpper` and `ToLower` functions accordingly, and added the ability to later define a specific BCP 47 language tag (not yet sure _how_, but the plumbing is laid).
> strings.Title - fix ability to handle unicode punctuation

- docs/content/usage.md
Partly addressing #1311 by clarifying how plugins interpret arguments.
> Clarify plugin documentation re: stdin

- docs/content/installing.md
`gomplate` is now available via MacPorts: https://ports.macports.org/port/gomplate
> docs: Add MacPorts installation instructions

- docs/content/config.md
- docs/content/usage.md
- internal/config/configfile.go
- internal/config/configfile_test.go
- internal/tests/integration/config_test.go
- internal/tests/integration/plugins_test.go
- plugins.go
- plugins_test.go
Fixes #1311 
Instead of only providing the input as the final arg to the plugin command, this allows providing the input as its stdin instead.
> Support piping input to plugin

- data/datasource_file.go
- internal/tests/integration/datasources_file_test.go
Fixes #1333
This isn't super-elegant, and it highlights a big flaw in the way datasources work right now in gomplate... _But_ this should all go away once the port to go-fsimpl is done.
> Reset cached mime-type when reading sub-datasources

- docs/content/config.md
- docs/content/usage.md
> Clarify that inputDir is read recursively

- docs-src/content/functions/tmpl.yml
- docs/content/functions/tmpl.md
- internal/tests/integration/tmpl_test.go
- template.go
- tmpl/tmpl.go
- tmpl/tmpl_test.go
Fixes #1363 
Two new functions to output the path and directory of the current template.
> New tmpl.Path/tmpl.PathDir functions

- crypto/ecdsa.go
- crypto/ecdsa_test.go
- docs-src/content/functions/crypto.yml
- docs/content/functions/crypto.md
- funcs/crypto.go
- funcs/crypto_test.go
ECDSAGenerateKey takes one of Go's supported named NIST curves and an
argument and returns a newly generated EC private key PEM encoded.
ECDSADerivePublicKey takes a PEM encoded EC private key and derives the
corresponding public key, which is returned PEM encoded.
> Add ECDSA generation functions to crypto funcs

- docs-src/content/functions/net.yml
- docs/content/functions/net.md
- funcs/net.go
- funcs/net_test.go
- go.mod
- go.sum
- internal/tests/integration/integration_test.go
- internal/tests/integration/net_test.go
I've added a few more functions to the `net` namespace:
- `net.CidrHost` to calculate host IP address from CIDR and host number, based on Terraform [`cidrhost`](https://www.terraform.io/language/functions/cidrhost) function
- `net.CidrNetmask` to return CIDR netmask in dotted-decimal IPv4 address syntax, based on Terraform [`cidrnetmask`](https://www.terraform.io/language/functions/cidrnetmask) function
- `net.CidrSubnets` to return a list of subnets from give CIDR and new netmask bits, based on Terraform [`cidrsubnet `](https://www.terraform.io/language/functions/cidrsubnet) function
- `net.CidrSubnetSizes` to calculate a sequence of consecutive IP address ranges within a particular CIDR prefix, based on Terraform [`cidrsubnets`](https://www.terraform.io/language/functions/cidrsubnets) …
> Add Terraform CIDR based functions

- funcs/net.go
> fix lint warning - it's OK that parseNetipPrefix isn't used yet

- gomplate.go
- gomplate_test.go
- internal/cmd/config.go
- internal/config/configfile.go
- template.go
- template_test.go
- template_unix_test.go
- template_windows_test.go
Some more general refactoring (following #1407) - this time removing the unnecessary indirection in `processTemplates`, and further simplifying the `tplate` struct, no longer storing the output file's path, but instead directly storing an `io.Writer`.
It seems like I'm also slowly removing references to the internal `config.Config` struct where not actually necessary. This should in theory help in future...
> Simplify template processing

- aws/ec2info_test.go
- aws/ec2meta.go
- aws/ec2meta_test.go
- aws/testutils.go
- gomplate_test.go
Changes:
* Start using the AWS SDK for retrieving instance data (to future proof against changes that might come in EC2 auth)
* Supports both IMDSv1 and IMDSv2 transparently
Fixes #848
> Add support for aws imdsv2

- docs-src/content/functions/crypto.yml
- docs/content/functions/crypto.md
- funcs/crypto.go
I intended to do this originally in #1305 as I'm not completely satisfied with how this works - see #1416
> Mark new AES functions experimental

- data/datasource.go
- docs/content/usage.md
- gomplate.go
- gomplate_test.go
- render.go
- render_test.go
- template.go
- template_test.go
- template_unix_test.go
- template_windows_test.go
Addresses #548 and #1097 by adding a new `gomplate.Renderer` type that exposes rendering functionality in gomplate for programmatic use. There's a couple example tests that outline some common ways to use this.
Instead of exporting the internal `config.Config` type I've opted to create new `gomplate.Options` and `gomplate.Template` types, which represent common options (datasources, etc) and templates (input text + output writer).
I've also refactored the current internals to use this new functionality.
Since the interface is brand new I'm marking it as experimental API - subject to change before v4. I'm hoping to get some feedback after v3.11 is released, after which point it'll stable API.
Fixes #551 
Fixes #1097 
Fixes #548 
> New experimental gomplate.Renderer API

- net/net_test.go
The `hairyhenderson.ca` record changed, and that really shouldn't have any effect on a gomplate unit test 🤦‍♂️
> Fixing flakey LookupIP test

- net/net_test.go
- render_test.go
> [3.11.x backport] Fixing flakey LookupIP test

- docs-src/content/functions/coll.yml
- docs-src/content/functions/conv.yml
- docs-src/content/functions/func_doc.md.tmpl
- docs-src/content/functions/math.yml
- docs-src/content/functions/strings.yml
- docs/content/functions/coll.md
- docs/content/functions/conv.md
- docs/content/functions/data.md
- docs/content/functions/math.md
- docs/content/functions/strings.md
- docs/content/syntax.md
- funcs/coll.go
- funcs/coll_test.go
- funcs/conv.go
- gomplate_test.go
- internal/tests/integration/collection_test.go
- internal/texttemplate/exec.go
- internal/texttemplate/exec_test.go
- internal/texttemplate/funcs.go
Deprecates `slice` in preparation for removal in a future major version of gomplate (not necessarily v4).
Adds `coll.GoSlice` to support the same behaviour as the `text/template` `slice` function (that was added after the gomplate `slice` function).
See #1461 for details!
> Add coll.GoSlice and deprecate slice alias

- .golangci.yml
- config.go
- context.go
- context_test.go
- conv/conv.go
- data/datasource.go
- funcs.go
- funcs/aws.go
- funcs/base64.go
- funcs/coll.go
- funcs/conv.go
- funcs/crypto.go
- funcs/data.go
- funcs/env.go
- funcs/file.go
- funcs/filepath.go
- funcs/gcp.go
- funcs/math.go
- funcs/net.go
- funcs/path.go
- funcs/random.go
- funcs/regexp.go
- funcs/sockaddr.go
- funcs/strings.go
- funcs/test.go
- funcs/time.go
- funcs/uuid.go
- gomplate_test.go
- libkv/consul.go
- render.go
The `// Deprecated:` comment annotations need to have an empty line above for them to be properly interpreted by `go doc`. This fixes that, and also converts references to functions or packages to proper links.
> Fixing deprecation annotation syntax

- docs/content/datasources.md
- internal/tests/integration/datasources_git_test.go
Just some tweaks and extra tests - datasource URLs that point to directories that don't end in `/` are a bad idea, and subpaths that begin with `//` are also a bad idea. These work right now because the git URL parsing is _special_...
Not sure if I'm going to keep this behaviour for gomplate v4 - depends how annoying it is to port to the go-fsimpl backend (#1336)
> Clarify git URL docs - stop implying subpaths starting with '//' are a good idea

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- funcs/strings.go
There was some confusion in #1535 between `split` and `strings.Split`, which I had intended to deprecate ages ago, but never got around to it...
I've deprecated all of the non-pipelineable functions with a notice to use `strings.*` instead.
This also clarifies (hopefully?) the docs for `strings.Split`. I've used the [stdlib `strings.Split`](https://pkg.go.dev/strings#Split) doc as a guide.
I'll eventually remove these functions, but not for a while as they're likely to be heavily used.
> Deprecate non-pipelineable strings aliases

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- funcs/strings.go
- strings/strings.go
- strings/strings_test.go
New `strings.SkipLines` function - basically a bit of syntactic sugar over `strings.SplitN`
> Add strings.SkipLines function

- coll/jq.go
- coll/jq_test.go
- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
- funcs/coll.go
- go.mod
- go.sum
- internal/tests/integration/collection_test.go
This PR adds support for the jq language to filter/transform complex data structures.
See [docs/content/functions/coll.md] for usage documentation.
Tasks:
Questions:
-> Yes, should be ok. Should be mentioned in the documentation.
-> Since there's no easy way to distinguish between an array with a single element and just a single element in the result it is kept the way it is done for `jsonpath`.
Future enhancements:
- Add variable binding (use gomplate variables in JQ expressions). It's not straight forward to implement in go templates.
Resolves #1584
> Add coll.JQ using gojq library

- coll/index.go
- coll/index_test.go
- docs-src/content/functions/coll.yml
- docs/content/functions/coll.md
- funcs/coll.go
Adds an alternative to the `index` built-in which supports pipeline use, and is more strict (errors when map key is not found, rather than returning zero value).
Related to #1545 
> New coll.Index function

- coll/jsonpath.go
- conv/conv.go
- crypto/pbkdf2.go
- data/data.go
- data/data_test.go
- data/datasource.go
- data/datasource_awssmp.go
- data/datasource_blob.go
- data/datasource_file.go
- data/datasource_http.go
- data/datasource_merge.go
- data/datasource_stdin.go
- data/datasource_vault.go
- file/file.go
- funcs/coll.go
- funcs/crypto.go
- funcs/random.go
- funcs/regexp.go
- funcs/strings.go
- funcs/test.go
- go.mod
- gomplate.go
- internal/config/configfile.go
- internal/conv/conv.go
- internal/tests/integration/datasources_vault_test.go
- test/test.go
- tmpl/tmpl.go
- vault/auth.go
- vault/vault.go
Replace uses of `github.com/pkg/errors` with `fmt.Errorf`. `pkg/errors` is now archived, and the `fmt.Errorf` support for error wrapping is now more idiomatic.
> Remove uses of pkg/errors

- internal/tests/integration/inputdir_unix_test.go
- render.go
I'd been ignoring the locally-failing `TestInputDir_RespectsUlimit` test because it passed on Linux. But after some deeper inspection it looks like it's an actual failure, and maybe the ulimit setting is not actually working on Linux during the test.
The leak is fairly obvious - it's a defer called in a loop that should be called in a separate function.
> Fix file descriptor leak

- random/random.go
`math/rand` no longer seeds to `1` by default, so calling `rand.Seed(time.Now().UnixNano())` is no longer necessary (and triggers a lint error). It's safe enough to just use the global `rand` funcs now.
> random: fix lint error on deprecated rand.Seed use

- docs/content/datasources.md
- internal/tests/integration/datasources_vault_test.go
- vault/auth.go
As of Vault 1.13.0, the AppID auth method is finally removed. See https://developer.hashicorp.com/vault/docs/deprecation/faq#q-what-should-i-do-if-i-use-mount-filters-appid-or-any-of-the-standalone-db-engines for details.
The AppID auth method has been deprecated since Vault 0.6.1, which came out in 2016. It therefore makes sense to remove gomplate support starting in the next major release.
> Remove support for obsolete Vault app-id auth

- .gitignore
- Makefile
- data/data_test.go
- plugins.go
- plugins_test.go
This adds a `test-remote-windows` make target that lets me run tests remotely on a Windows VM with a minimum of fuss. There are some rough edges, but it's a good start. This should help me fix Windows issues much faster in future...
> Add make test-remote-windows target to run tests on remote Windows host

- Dockerfile
- docs/content/config.md
- internal/config/configfile.go
- internal/config/configfile_test.go
- internal/tests/integration/plugins_test.go
- plugins.go
- plugins_test.go
> New plugin args option

- data/data.go
- docs-src/content/functions/data.yml
- docs/content/functions/data.md
This updates the description of the header parameter to data.CSVBy* functions from *comma-separated list of column names* to *character-separated list of column names using delim as separator*.
Fixes #1711
> Clarified documentation of data.CSVBy* functions

- docs/content/usage.md
Fixes #1686.
The example wasn't working, because the context wasn't being passed in to `template`.
> Fix output-map usage docs

- Makefile
There are scenarios in which `CGO_ENABLED=1` has to be set when building the `gomplate` binary. 
Specifically building the binary in FIPS-enabled mode requires that `CGO_ENABLED=1` and `GOEXPERIMENT=boringcrypto` are set.
However, this is not possible with the Makefile hardcoding `CGO_ENABLED=0`. 
This PR makes changes to allow the value of the `CGO_ENABLED` environment variable to be used if it is set. 
If the `CGO_ENABLED` environment variable is not set, then `CGO_ENABLED` defaults to 0.
> Update Makefile to use CGO_ENABLED environment variable

- funcs/strings.go
- funcs/strings_test.go
Sets the `NoLower` option so that acronyms are not lowercased.
> Make `strings.Title` not lowercase acronyms

- docs/content/datasources.md
In response to <https://github.com/hairyhenderson/gomplate/issues/862#issuecomment-1735529671>
> document the workaround for Vault KV secrets engine - version 2

- docs/content/usage.md
Correctly formats the example and makes it equal to the other one: https://github.com/hairyhenderson/gomplate/blob/d4d0df967d5ced07acde0c1e239da413b661f7bb/docs/content/_index.md#L24
> docs: format user template in hello example

- docs/content/syntax.md
Hello, just had a scenario where I needed to access a nested YAML in which some key names should've been fetched from an environment variable. Hopefully this explains how to combine multiple nested keys with some additional functions if needed.
> Explain that `index` supports nested keys

- data/data.go
- data/data_test.go
- data/datasource.go
- data/mimetypes.go
- docs-src/content/functions/data.yml
- funcs/data.go
- go.mod
- go.sum
- internal/tests/integration/datasources_file_test.go
Fixes #1601
This adds CUE support to gomplate as a native datasource format, as well as `data.CUE`/`cue` and `data.ToCUE`/`toCUE` functions to allow inline parsing and rendering.
CUE has support for [modules and packages](https://cuelang.org/docs/concepts/packages/) (ability to import data from other files), which doesn't work just yet. ~Key to this is providing a filename, which is awkward with the current `parseData` signature.~
~I'll keep this in draft until I'm happy with a solution for this (or until I decide to simply not support importing).~
At least to start, CUE support will be single-file only, with no support for importing local packages.
> Initial basic support for CUE

- .github/workflows/docker.yml
- Dockerfile
Gets the image scan to pass for CVE-2023-5363. The gomplate binary isn't vulnerable since it doesn't use OpenSSL, but the presence of the older version of the library trips scanners.
> Workaround for CVE-2023-5363

- .github/workflows/build.yml
- data/datasource_git.go
- internal/datafs/fsys.go
- internal/datafs/wdfs.go
- internal/datafs/wdfs_test.go
- internal/tests/integration/datasources_git_test.go
- template.go
Handling of relatively obscure forms of Windows file paths was broken by the security fixes in Go 1.21.4. This PR fixes the logic to be more in-line with how Windows itself categorizes and parses paths.
There's probably an opportunity for more refactoring, but this'll do for now.
This also updates the CI to expose bugs when dealing with non-current volumes on Windows.
> Fix the wdFS behaviour due to Go 1.21.4's changes to IsAbs

- docs-src/content/functions/semver.yaml
- docs-src/content/functions/semver.yml
- docs/content/functions/semver.md
- funcs.go
- funcs/semver.go
- funcs/semver_test.go
- semver.Version: new a SemVer struct.
- semver.MatchConstraint: match in arg with semver constraint string.
refer to: https://github.com/Masterminds/sprig/blob/master/semver.go
Based on: #1828
> feat(funcs): add semver functions

- aws/ec2info_test.go
- context_test.go
- data/datasource_blob_test.go
- data/datasource_env_test.go
- data/datasource_git_test.go
- internal/cmd/config_test.go
- internal/cmd/logger_test.go
- libkv/consul_test.go
- render_test.go
- vault/auth_test.go
- vault/vault_test.go
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
This PR also splits large test cases into subtests. This is useful because VSCode is able to run subtest separately
> test: use `t.Setenv` to set env vars in tests

- docs/content/config.md
- docs/content/usage.md
- gomplate_test.go
- internal/cmd/config.go
- internal/cmd/main.go
- internal/config/configfile.go
- internal/config/configfile_test.go
- internal/tests/integration/config_test.go
- internal/tests/integration/integration_test.go
- internal/tests/integration/missing_key_test.go
- render.go
- template.go
This pull request allow to control behavior in case of non-existent keys. It described in the issue #1948
> Add missing-key flag to manage behavior in case of non-existing key

- docs/content/config.md
- internal/config/types.go
- internal/tests/integration/config_test.go
A precursor to #1976, which will be re-done in v4.1.0 or so.
> Warn when deprecated k=v array form is used for templates

- config.go
- docs/content/config.md
- docs/content/usage.md
- internal/cmd/config.go
- internal/cmd/main.go
- internal/config/configfile.go
- internal/tests/integration/gomplateignore_test.go
- template.go
- template_unix_test.go
- template_windows_test.go
Fixes #1911 
This PR added a CLI option `--exclude-processing` and an equivelent config entry `excludeProcessing`, if it is set, the matching files will go with a different code path `copyFileToOutDir`.
To make the code reusable, the codes about file IO are offloaded from`fileToTemplate` into `readInFile`, `getOutfileHandler`, and are called by `copyFileToOutDir` as well. 
**How to test:**
Have a jpeg file in `in` directory.
**case 1: (test cli argument `--exclude-processing`)**
run:
`./gomplate --exclude-processing '*.jpg' --input-dir=in --output-dir=out`
the *.jpg exists in `out` directory  
**case 2: (test config file entry `excludeProcessing`)**
have a `.gomplate.yaml` file in the directory:
`
inputDir: in/
outputDir: out/
excludeProcessing:
- '*.jpg'
`
run:
`./gomplate --input-dir=in …
> Add --exclude-processing option

- config.go
- docs/content/config.md
- docs/content/usage.md
- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/config/configfile.go
- internal/iohelpers/writers.go
- internal/tests/integration/basic_test.go
- internal/tests/integration/gomplateignore_test.go
- render.go
- template.go
- template_test.go
In https://github.com/hairyhenderson/gomplate/issues/430 this option was added, with the intention to make it the new behaviour in v4.
> feat!: Always suppress empty output

- docs-src/content/functions/coll.yml
- internal/funcs/coll.go
- internal/funcs/coll_test.go
- internal/tests/integration/collection_test.go
> feat: coll.Pick and coll.Omit now support slice of strings as input

- .github/workflows/docs.yml
- Makefile
- docs/content/functions/data.md
Some docs updates have been missed (see https://github.com/hairyhenderson/gomplate/pull/2070 and also the updates made in #1781 were missed). This attempts to render docs in CI and fail if they're not up-to-date.
> ci(docs): Require up-to-date function docs

- gomplate.go
- gomplate_test.go
- render.go
- template.go
- template_test.go
> chore: add files missed from PR 2083

- internal/datafs/wdfs.go
Clearing out a TODO - file path.IsAbs checks that name starts with `/` on UNIX-like OSes, and on Windows the `/` check is integral as well. The logic is _slightly_ different, but I think this is simpler and should still work.
> fix: Simplify condition to just use filepath.IsAbs

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- internal/funcs/strings.go
- strings/strings.go
- strings/strings_fuzz_test.go
- strings/strings_test.go
Breaking API change for 4.0 - instead of silently doing nothing when invalid input is provided, the function now errors.
> feat(strings)!: Update strings.Indent to error on bad input instead of silently doing nothing

- internal/funcs/regexp.go
- internal/funcs/regexp_test.go
- regexp/regexp.go
- regexp/regexp_test.go
Previously, when an invalid regular expression was given to `regex.Replace` or `regex.Match`, the functions would panic. Now, the functions return an error instead.
> chore(api)!: Return errors instead of panicking on regexp functions

- config.go
- config_test.go
- gomplate.go
- internal/cmd/config.go
- internal/cmd/config_test.go
- template.go
- template_test.go
When I merged #2094 I didn't mean to export all of `Config`'s methods - the ones only needed for parsing don't need to be exported.
> chore(api)!: Unexport some Config methods

- docs/content/functions/strings.md
Minor doc update: The current example is missing a trailing `'`.
> Fix example for Strings.Trim

- docs-src/content/functions/strings.yml
Missed in #2107 - the fix needs to be in the source the docs were generated from too!
> docs: Sync fix from #2107 to source

- conv/conv.go
- conv/conv_test.go
- docs-src/content/functions/conv.yml
- docs/content/functions/conv.md
- internal/funcs/coll.go
- internal/funcs/conv.go
- internal/funcs/crypto.go
- internal/funcs/math.go
- internal/funcs/math_test.go
- internal/funcs/net.go
- internal/funcs/random.go
- internal/funcs/regexp.go
- internal/funcs/strings.go
- internal/funcs/time.go
- internal/tests/integration/math_test.go
This is a breaking change, but will result in more correct rendering.
Instead of quietly returning `0`, a number of functions in the `conv` namespace will now return an error if the input is invalid.
This includes:
- `conv.ToInt64`, `conv.ToInt`, `conv.ToInt64s`, `conv.ToInts`, `conv.ToFloat64`, `conv.ToFloat64s`, `conv.ParseInt`, `conv.ParseFloat`, `conv.ParseUint`, `conv.Atoi`
Because these functions are used by some other functions, this introduces stricter input validation for these functions:
- `coll.Flatten`
- `crypto.PBKDF2`, `crypto.Bcrypt`, `crypto.RSAGenerateKey`, `crypto.EncryptAES`, `crypto.DecryptAES`, `crypto.DecryptAESBytes`
- `math.Abs`, `math.Add`, `math.Mul`, `math.Sub`, `math.Div`, `math.Rem`, `math.Pow`, `math.Seq`, `math.Max`, `math.Min`, `math.Ceil`, `math.Floor`, …
> chore(api)!: Error instead of returning 0 on invalid inputs to conv.* functions

- docs/content/datasources.md
- internal/datafs/mergefs.go
- internal/datafs/reader.go
- internal/tests/integration/datasources_http_test.go
- internal/tests/integration/datasources_merge_test.go
- internal/tests/integration/integration_test.go
Fixes #1606 
This adds a new environment variable `GOMPLATE_TYPE_PARAM` which allows switching out the `type` parameter to another name for those rare cases when people need to send an HTTP server a parameter named `type`!
> feat: Add ability to override 'type' query parameter name

- internal/tests/integration/strings_test.go
I think this is the last step toward getting #2121 solved.
`TestStrings_Repeat` had `math.MaxInt64` hard-coded, which fails in the wrong way on 32bit systems (negative count, rather than overflow)
> fix(test): Fix strings.Repeat test that failed in the wrong way on 32bit

- docs/content/datasources.md
Partly related to #2144 - the docs were behind and still documented the v3 workaround for kv2 support.
> docs(datasources): clarify state of Vault KV v2 support

- docs-src/content/functions/strings.yml
- docs/content/functions/strings.md
- internal/funcs/strings.go
- internal/funcs/strings_test.go
Closes https://github.com/hairyhenderson/gomplate/issues/2134
Wrapping two more functions from strings.
- strings.TrimLeft
- strings.TrimRight
Signed-off-by: Javier Solana <javier.solana@cabify.com>
> feat(strings): New functions TrimRight and TrimLeft

- .github/workflows/release-please.yml
- go.mod
the v4.1.0 release [failed](https://github.com/hairyhenderson/gomplate/actions/runs/9819804876/job/27113740454), so I used this to redo the release.
the main issue was permissions - there was a tag protection rule applied incorrectly
> ci(fix): fix broken release workflow

- .golangci.yml
- coll/coll_test.go
- coll/index.go
- conv/conv.go
- conv/conv_test.go
- conv/evalargs.go
- crypto/rsa_test.go
- docs-src/content/functions/conv.yml
- docs/content/functions/conv.md
- internal/cidr/cidr.go
- internal/cmd/config_test.go
- internal/conv/conv_test.go
- internal/datafs/wdfs_test.go
- internal/funcs/conv_test.go
- internal/funcs/math_test.go
- internal/funcs/net.go
- internal/funcs/strings.go
- internal/funcs/time.go
- internal/iohelpers/writers_test.go
- internal/tests/integration/inputdir_unix_test.go
- internal/tests/integration/integration_test.go
- internal/texttemplate/funcs.go
- random/random_test.go
- strings/strings.go
- strings/strings_fuzz_test.go
- test/test.go
Fixes lint errors that have cropped up in Go 1.23 and/or golangci-lint 1.60/61...
Also replaces `exportloopref` with `copyloopvar`.
This _ever so slightly_ changes behaviour when certain numbers can't be converted (due to overflow). The docs used to say behaviour was undefined - this defines it (with errors!).
> fix(lint): Fix or ignore lint errors

- .github/workflows/docs.yml
- docs/content/usage.md
- env/env.go
- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/datafs/getenv.go
- internal/tests/integration/config_test.go
- internal/tests/integration/datasources_consul_test.go
In https://github.com/hairyhenderson/gomplate/pull/2202 the root issue was that the user was running in an unreadable working directory, and so gomplate errored with a message like:
```
Error: fsys for path .gomplate.yaml: resolve local path ".gomplate.yaml": getwd: stat .: permission denied
```
Rather than ignore errors when the default config file can't be read (which will hide real failures and perform the wrong behaviour potentially), this PR adds the ability to set `--config` or `$GOMPLATE_CONFIG` to an empty string, which will cause the config file parsing code to be skipped entirely.
> feat(config): Allow avoiding reading default config file

- .github/workflows/docs.yml
- docs/content/datasources.md
Muffet's [found a couple issues](https://github.com/hairyhenderson/gomplate/actions/runs/11759396946/job/32758826541): an upstream link has started rejecting GETs from robots, and the Vault docs have changed an anchor name...
> docs(links): Fix broken link

- docs/content/usage.md
Using backticks in the gomplate like so will result in error: `*.png: command not found`:
```
$ gomplate --exclude-processing `*.png` --input-dir in/ --output-dir out/
```
Fixed the command:
```
$ gomplate --exclude-processing '*.png' --input-dir in/ --output-dir out/
```
> Minor fix in documentation related to `--exclude-processing`

- internal/datafs/reader.go
- internal/datafs/reader_test.go
- internal/tests/integration/datasources_file_test.go
> fix(datasources): Properly handle datasources and other URLs beginning with '../'

- internal/datafs/fsys.go
- internal/datafs/vaultauth.go
- internal/tests/integration/datasources_vault_ec2_test.go
- internal/tests/integration/datasources_vault_iam_test.go
- internal/tests/integration/datasources_vault_test.go
- internal/tests/integration/test_ec2_utils_test.go
> feat(fs): Support Vault AWS IAM auth

- docs/content/syntax.md
Minor thing I found reading through the example on external templates
> docs(fix): Quotation in external templates example

- internal/datafs/fsurl.go
- internal/datafs/fsurl_test.go
- internal/datafs/fsys.go
- internal/datafs/reader.go
> fix(datasources): Fix aws+sm bug when reading secrets not starting with slash

- internal/datafs/mergefs.go
- internal/datafs/mergefs_test.go
- internal/tests/integration/datasources_merge_test.go
Fixes #2273 by ensuring that each sub-file is only opened once.
> fix(fs): fix mergefs bug where files were opened too many times

- internal/datafs/reader.go
- internal/datafs/reader_test.go
Fixes #2190; the second part - see https://github.com/hairyhenderson/gomplate/issues/2190#issuecomment-2547117657
> fix(datasources): Properly support aws+sm with args

- internal/cmd/config.go
- internal/cmd/config_test.go
- internal/datafs/default.go
- internal/datafs/envfs.go
- internal/datafs/envfs_test.go
- internal/datafs/fsurl.go
- internal/datafs/mergefs.go
- internal/datafs/mergefs_test.go
- internal/datafs/stdinfs.go
- internal/datafs/stdinfs_test.go
- internal/datafs/wdfs.go
- render.go
Handling some new linter warnings, and also unexporting some things in `internal/` that didn't need to be exported.
> fix(lint): Address new lint warnings

- .github/workflows/docs.yml
`localhost` seems to resolve to `[::1]` now, where hugo is explicitly binding to 127.0.0.1. That's why it's been failing for a while.
> ci(docs): Fix muffet command

- CONTRIBUTING.md
- config.go
- docs-src/content/functions/conv.yml
- docs-src/content/functions/data.yml
- docs-src/content/functions/filepath.yml
- docs-src/content/functions/math.yml
- docs-src/content/functions/semver.yml
- docs-src/content/functions/time.yml
- docs/content/config.md
- docs/content/datasources.md
- docs/content/functions/conv.md
- docs/content/functions/data.md
- docs/content/functions/filepath.md
- docs/content/functions/math.md
- docs/content/functions/semver.md
- docs/content/functions/time.md
- docs/content/syntax.md
- docs/content/usage.md
- env/env.go
- internal/cidr/cidr.go
- internal/funcs/file_test.go
- internal/funcs/semver_test.go
- internal/iohelpers/write_test.go
- internal/urlhelpers/urlhelpers_test.go
Found via `codespell -L fom,fo,wil,nd,wit` and `typos --hidden --format brief`
> docs(fix): fix typos

- .github/workflows/release.yml
It seems that home-brew now auto-bumps packages (for example: https://github.com/Homebrew/homebrew-core/pull/210739), so there's no point in doing this on release anymore!
> ci(homebrew): Let homebrew auto-bump
